### ISSUE TITLE
Error trying to open up Disk Drive blockin server

### ISSUE THREAD

**Issue by ArsiTheFox** [SquidDev-CC/CC-Tweaked#1115]
### Minecraft Version

1.18.x

### Version

1.100.6

### Details

ERROR: `[13:41:10] [Server thread/ERROR] [minecraft/LevelChunk]: A BlockEntity type dan200.computercraft.shared.peripheral.diskdrive.TileDiskDrive has thrown an exception trying to write state. It will not persist, Report this to the mod author
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.LockCode.m_19109_(net.minecraft.nbt.CompoundTag)" because "this.lockCode" is null
        at dan200.computercraft.shared.peripheral.diskdrive.TileDiskDrive.m_183515_(TileDiskDrive.java:162) ~[cc-tweaked-1.18.2-1.100.6.jar%2357!/:1.100.6] {re:classloading}
        at net.minecraft.world.level.block.entity.BlockEntity.m_187482_(BlockEntity.java:77) ~[server-1.18.2-20220404.173914-srg.jar%23174!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.world.level.block.entity.BlockEntity.m_187480_(BlockEntity.java:64) ~[server-1.18.2-20220404.173914-srg.jar%23174!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.world.level.chunk.LevelChunk.m_8051_(LevelChunk.java:359) ~[server-1.18.2-20220404.173914-srg.jar%23174!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:supplementaries.mixins.json:LevelChunkMixin,pl:mixin:A}
        at net.minecraft.world.level.chunk.storage.ChunkSerializer.m_63454_(ChunkSerializer.java:332) ~[server-1.18.2-20220404.173914-srg.jar%23174!/:?] {re:classloading}
        at net.minecraft.server.level.ChunkMap.m_140258_(ChunkMap.java:771) ~[server-1.18.2-20220404.173914-srg.jar%23174!/:?] {re:classloading,re:mixin}
        at net.minecraft.server.level.ChunkMap.m_198874_(ChunkMap.java:738) ~[server-1.18.2-20220404.173914-srg.jar%23174!/:?] {re:classloading,re:mixin}
        at net.minecraft.server.level.ChunkMap.m_140353_(ChunkMap.java:462) ~[server-1.18.2-20220404.173914-srg.jar%23174!/:?] {re:classloading,re:mixin}
        at net.minecraft.server.level.ChunkMap.m_140280_(ChunkMap.java:426) ~[server-1.18.2-20220404.173914-srg.jar%23174!/:?] {re:classloading,re:mixin}
        at net.minecraft.server.level.ServerChunkCache.m_201698_(ServerChunkCache.java:313) ~[server-1.18.2-20220404.173914-srg.jar%23174!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
        at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:281) ~[server-1.18.2-20220404.173914-srg.jar%23174!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,re:classloading,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,pl:mixin:APP:botania_xplat.mixins.json:MixinServerLevel,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:supplementaries.mixins.json:ServerLevelMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:902) ~[server-1.18.2-20220404.173914-srg.jar%23174!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:A}
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:326) ~[server-1.18.2-20220404.173914-srg.jar%23174!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[server-1.18.2-20220404.173914-srg.jar%23174!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[server-1.18.2-20220404.173914-srg.jar%23174!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23174!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:A}
        at java.lang.Thread.run(Thread.java:833) [?:?] {}`
        
       
When right clicking a DiskDrive it fails to open and nothing happens in the server. When I check server console that pops up

**Comment by SquidDev** [comment]
Thanks for reporting! I believe this is the same behaviour as https://github.com/cc-tweaked/CC-Tweaked/issues/1109. Hoping to get a release out soonish, but downgrading to 1.100.5 should also fix it.

**Comment by ArsiTheFox** [comment]
Oh sorry, seen this issue was already posted, my bad
