### ISSUE TITLE
[1.19] ComputerCraft JEI plugin crashes with newest JEI/REI

### ISSUE THREAD

**Issue by Saereth** [SquidDev-CC/CC-Tweaked#1116]
### Minecraft Version

1.18.x

### Version

cc-tweaked-1.19-1.100.7

### Details

jei-1.19-forge-11.0.0.206

Relevant Log section:

```

[19:21:42] [Render thread/INFO]: Registering item subtypes: computercraft:jei ...
[19:21:42] [Render thread/ERROR]: Caught an error from mod plugin: class dan200.computercraft.shared.integration.jei.JEIComputerCraft computercraft:jei
java.lang.NoSuchMethodError: 'void mezz.jei.api.registration.ISubtypeRegistration.registerSubtypeInterpreter(net.minecraft.world.item.Item, mezz.jei.api.ingredients.subtypes.IIngredientSubtypeInterpreter)'
	at dan200.computercraft.shared.integration.jei.JEIComputerCraft.registerItemSubtypes(JEIComputerCraft.java:55) ~[cc-tweaked-1.19-1.100.7.jar%2390!/:1.100.7]
	at mezz.jei.common.load.PluginLoader.lambda$new$0(PluginLoader.java:83) ~[jei-1.19-forge-11.0.0.206.jar%23124!/:11.0.0.206]
	at mezz.jei.common.load.PluginCaller.callOnPlugins(PluginCaller.java:25) ~[jei-1.19-forge-11.0.0.206.jar%23124!/:11.0.0.206]
	at mezz.jei.common.load.PluginLoader.<init>(PluginLoader.java:83) ~[jei-1.19-forge-11.0.0.206.jar%23124!/:11.0.0.206]
	at mezz.jei.common.startup.JeiStarter.start(JeiStarter.java:79) ~[jei-1.19-forge-11.0.0.206.jar%23124!/:11.0.0.206]
	at mezz.jei.forge.startup.ClientLifecycleHandler.startJei(ClientLifecycleHandler.java:84) ~[jei-1.19-forge-11.0.0.206.jar%23124!/:11.0.0.206]
	at mezz.jei.forge.startup.StartEventObserver.transitionState(StartEventObserver.java:137) ~[jei-1.19-forge-11.0.0.206.jar%23124!/:11.0.0.206]
	at mezz.jei.forge.startup.StartEventObserver.onEvent(StartEventObserver.java:100) ~[jei-1.19-forge-11.0.0.206.jar%23124!/:11.0.0.206]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-6.0.0.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-6.0.0.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-6.0.0.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-6.0.0.jar%232!/:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_5859_(ClientPacketListener.java:1313) ~[client-1.19-20220607.102129-srg.jar%23179!/:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:35) ~[client-1.19-20220607.102129-srg.jar%23179!/:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:11) ~[client-1.19-20220607.102129-srg.jar%23179!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.19-20220607.102129-srg.jar%23179!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.19-20220607.102129-srg.jar%23179!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.19-20220607.102129-srg.jar%23179!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.19-20220607.102129-srg.jar%23179!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[client-1.19-20220607.102129-srg.jar%23179!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1028) ~[client-1.19-20220607.102129-srg.jar%23179!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:660) ~[client-1.19-20220607.102129-srg.jar%23179!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.19-20220607.102129-srg.jar%23179!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19-41.0.38.jar%2317!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.1.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.1.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.1.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.1.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.1.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.1.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.1.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:155) [bootstraplauncher-1.1.0.jar:?]

```

**Comment by Saereth** [comment]
Did this get released somewhere or am I just blind? :P Thanks again btw, love the mod!

**Comment by SquidDev** [comment]
Not yet, no - there's some other 1.19 issues (#1117) I need to fix. You can grab it from GH actions right now.

**Comment by Saereth** [comment]
ok cool thanks!

**Comment by Saereth** [comment]
Is the version in the GH actions ok for us to use in this pack update? We were hoping to push an update to FTB One today.

**Comment by SquidDev** [comment]
Yep, probably. Afraid I'm unlikely to push another proper build until Forge has an RB out - there's some other breaking changes coming up.

**Comment by Saereth** [comment]
ok thanks for the heads up, sounds good.
