### ISSUE TITLE
Turtles have some bug for crash

### ISSUE THREAD

**Issue by blackvccat** [SquidDev-CC/CC-Tweaked#1450]
### Minecraft Version

1.19.x

### Version

1.101.2

### Details

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraftforge.client.extensions.IForgeTransformation.push(IForgeTransformation.java:51) ~[forge-1.19.2-43.2.11-universal.jar%23324!/:?] {re:classloading}
	at dan200.computercraft.client.render.TileEntityTurtleRenderer.renderUpgrade(TileEntityTurtleRenderer.java:154) ~[cc-tweaked-1.19.2-1.101.2.jar%23284!/:1.101.2] {re:classloading}
	at dan200.computercraft.client.render.TileEntityTurtleRenderer.render(TileEntityTurtleRenderer.java:137) ~[cc-tweaked-1.19.2-1.101.2.jar%23284!/:1.101.2] {re:classloading}
	at dan200.computercraft.client.render.TileEntityTurtleRenderer.m_6922_(TileEntityTurtleRenderer.java:44) ~[cc-tweaked-1.19.2-1.101.2.jar%23284!/:1.101.2] {re:classloading}
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112284_(BlockEntityRenderDispatcher.java:116) ~[client-1.19.2-20220805.130853-srg.jar%23319!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:supplementaries.mixins.json:BlockEntityRendererDispatcherMixin,pl:mixin:APP:flywheel.mixins.json:BlockEntityRenderDispatcherAccessor,pl:mixin:APP:armourersworkshop-mixins.json:BlockEntityRenderDispatcherMixin,pl:mixin:A}
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.lambda$renderTileEntity$0(BlockEntityRenderDispatcher.java:86) ~[client-1.19.2-20220805.130853-srg.jar%23319!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:supplementaries.mixins.json:BlockEntityRendererDispatcherMixin,pl:mixin:APP:flywheel.mixins.json:BlockEntityRenderDispatcherAccessor,pl:mixin:APP:armourersworkshop-mixins.json:BlockEntityRenderDispatcherMixin,pl:mixin:A}
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112278_(BlockEntityRenderDispatcher.java:163) ~[client-1.19.2-20220805.130853-srg.jar%23319!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:supplementaries.mixins.json:BlockEntityRendererDispatcherMixin,pl:mixin:APP:flywheel.mixins.json:BlockEntityRenderDispatcherAccessor,pl:mixin:APP:armourersworkshop-mixins.json:BlockEntityRenderDispatcherMixin,pl:mixin:A}
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112267_(BlockEntityRenderDispatcher.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23319!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:supplementaries.mixins.json:BlockEntityRendererDispatcherMixin,pl:mixin:APP:flywheel.mixins.json:BlockEntityRenderDispatcherAccessor,pl:mixin:APP:armourersworkshop-mixins.json:BlockEntityRenderDispatcherMixin,pl:mixin:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1938) ~[client-1.19.2-20220805.130853-srg.jar%23319!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:playerAnimator-common.mixins.json:firstPerson.LevelRendererMixin,pl:mixin:APP:supplementaries-common.mixins.json:LevelRendererMixin,pl:mixin:APP:supplementaries-common.mixins.json:ParrotMixin,pl:mixin:APP:supermartijn642corelib.mixins.json:LevelRendererMixin,pl:mixin:APP:flywheel.mixins.json:FixFabulousDepthMixin,pl:mixin:APP:flywheel.mixins.json:LevelRendererAccessor,pl:mixin:APP:scena.mixins.json:client.LevelRendererBeforeDebugRenderingHookMixin,pl:mixin:APP:create.mixins.json:LevelRendererMixin,pl:mixin:APP:flywheel.mixins.json:LevelRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1577) ~[client-1.19.2-20220805.130853-srg.jar%23319!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:supplementaries-common.mixins.json:GameRendererMixin,pl:mixin:APP:armourersworkshop-compatibility-mixins.json:AbstractGameRendererMixin,pl:mixin:APP:create.mixins.json:GameRendererMixin,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor,pl:mixin:A}
-- Block Entity Details --
Details:
	Name: computercraft:turtle_normal // dan200.computercraft.shared.turtle.blocks.TileTurtle
	Block: Block{computercraft:turtle_normal}[facing=south,waterlogged=false]
	Block location: World: (47,66,181), Section: (at 15,2,5 in 2,4,11; chunk contains blocks 32,-64,176 to 47,319,191), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Block: Block{computercraft:turtle_normal}[facing=south,waterlogged=false]
	Block location: World: (47,66,181), Section: (at 15,2,5 in 2,4,11; chunk contains blocks 32,-64,176 to 47,319,191), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
Stacktrace:
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112278_(BlockEntityRenderDispatcher.java:163) ~[client-1.19.2-20220805.130853-srg.jar%23319!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:supplementaries.mixins.json:BlockEntityRendererDispatcherMixin,pl:mixin:APP:flywheel.mixins.json:BlockEntityRenderDispatcherAccessor,pl:mixin:APP:armourersworkshop-mixins.json:BlockEntityRenderDispatcherMixin,pl:mixin:A}
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112267_(BlockEntityRenderDispatcher.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23319!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:supplementaries.mixins.json:BlockEntityRendererDispatcherMixin,pl:mixin:APP:flywheel.mixins.json:BlockEntityRenderDispatcherAccessor,pl:mixin:APP:armourersworkshop-mixins.json:BlockEntityRenderDispatcherMixin,pl:mixin:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1938) ~[client-1.19.2-20220805.130853-srg.jar%23319!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:playerAnimator-common.mixins.json:firstPerson.LevelRendererMixin,pl:mixin:APP:supplementaries-common.mixins.json:LevelRendererMixin,pl:mixin:APP:supplementaries-common.mixins.json:ParrotMixin,pl:mixin:APP:supermartijn642corelib.mixins.json:LevelRendererMixin,pl:mixin:APP:flywheel.mixins.json:FixFabulousDepthMixin,pl:mixin:APP:flywheel.mixins.json:LevelRendererAccessor,pl:mixin:APP:scena.mixins.json:client.LevelRendererBeforeDebugRenderingHookMixin,pl:mixin:APP:create.mixins.json:LevelRendererMixin,pl:mixin:APP:flywheel.mixins.json:LevelRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1577) ~[client-1.19.2-20220805.130853-srg.jar%23319!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:supplementaries-common.mixins.json:GameRendererMixin,pl:mixin:APP:armourersworkshop-compatibility-mixins.json:AbstractGameRendererMixin,pl:mixin:APP:create.mixins.json:GameRendererMixin,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1191) ~[client-1.19.2-20220805.130853-srg.jar%23319!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:supplementaries-common.mixins.json:GameRendererMixin,pl:mixin:APP:armourersworkshop-compatibility-mixins.json:AbstractGameRendererMixin,pl:mixin:APP:create.mixins.json:GameRendererMixin,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23319!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:customskinloader:MinecraftTransformer,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:customskinloader:MinecraftTransformer,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23319!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:customskinloader:MinecraftTransformer,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:customskinloader:MinecraftTransformer,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23319!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23319!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.11.jar%23154!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%23140!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%23140!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%23140!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%23140!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%23140!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%23140!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%23140!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?] {}
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58) [JavaWrapper.jar:?] {}
	at oolloo.jlw.Wrapper.main(Wrapper.java:51) [JavaWrapper.jar:?] {}

**Comment by piprett** [comment]
I blame OptiFine, consider [Oculus](https://modrinth.com/mod/oculus).
See #1436

**Comment by blackvccat** [comment]
ok
