### ISSUE TITLE
Game client crashes on teleport with pocket computer in hands

### ISSUE THREAD

**Issue by semas-vhd** [SquidDev-CC/CC-Tweaked#1765]
### Minecraft Version

1.20.x

### Version

1.110.1

### Details

When I teleport with "/home" command to saved location with pocket computer in hands, game crashes. Also, if I teleport without pocket computer in hands, game doesn't crash, but once I switch to pocket computer after that, game crashes again. I've tried it with pocket computer turned off, result is the same.

[log.txt](https://github.com/cc-tweaked/CC-Tweaked/files/14762431/log.txt)
[crash-2024-03-26_18.51.01-client.txt](https://github.com/cc-tweaked/CC-Tweaked/files/14762433/crash-2024-03-26_18.51.01-client.txt)

```
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at dan200.computercraft.core.terminal.Terminal.getBackgroundColourLine(Terminal.java:249)
	at dan200.computercraft.client.render.text.FixedWidthFontRenderer.drawTerminalBackground(FixedWidthFontRenderer.java:153)
	at dan200.computercraft.client.render.text.FixedWidthFontRenderer.drawTerminal(FixedWidthFontRenderer.java:191)
	at dan200.computercraft.client.render.PocketItemRenderer.renderItem(PocketItemRenderer.java:77)
	at dan200.computercraft.client.render.ItemMapLikeRenderer.renderItemFirstPersonCenter(ItemMapLikeRenderer.java:134)
	at dan200.computercraft.client.render.ItemMapLikeRenderer.renderItemFirstPerson(ItemMapLikeRenderer.java:42)
	at dan200.computercraft.client.ClientHooks.onRenderHeldItem(ClientHooks.java:80)

```

**Comment by Lemmmy** [comment]
Probably not relevant, but I should note that this happened on SwitchCraft ([ref](<https://discord.com/channels/198130613759246337/198130613759246337/1222229251345092679>))
