### ISSUE TITLE
[Crash, Fabric, 1.20.1] Seeing a Turtle through an Immersive Portal crashes the game

### ISSUE THREAD

**Issue by Flexico** [SquidDev-CC/CC-Tweaked#1775]
### Minecraft Version

1.20.x

### Version

1.110.0

### Details

Version Info
    Minecraft, 1.20.1
    CC:Tweaked 1.110.0
    Immersive Portals 3.3.9 Fabric

Are you using OptiFine?: No

Steps to Reproduce
Place a turtle
Set up portals so that you can see the turtle(s) from beyond the render distance
Look through portal

Crash report (~/logs/latest.log)
https://pastebin.com/02FNRPq4

I'm posting this both here and on IP's issue log

**Comment by SquidDev** [comment]
Thanks for the report!

```
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_239.method_17783()" because "hit" is null
	at dan200.computercraft.client.render.TurtleBlockEntityRenderer.render(TurtleBlockEntityRenderer.java:58) ~[cc-tweaked-1.20.1-fabric-1.110.0.jar:?]
	at dan200.computercraft.client.render.TurtleBlockEntityRenderer.method_3569(TurtleBlockEntityRenderer.java:29) ~[cc-tweaked-1.20.1-fabric-1.110.0.jar:?]
	at net.minecraft.class_824.method_23079(class_824.java:90) ~[client-intermediary.jar:?]
```

Hah, that's our first NPE for a while. Should be easy to fix at least.
