### ISSUE TITLE
Crash after teleport

### ISSUE THREAD

**Issue by AlmightyAnubis** [SquidDev-CC/CC-Tweaked#1779]
### Minecraft Version

1.20.x

### Version

forge-1.110.1

### Details

I used a Pocket Computer from Computercraft to dial a stargate from the stargate journey mod using a wireless connection. All of that went well, but after I went through the gate and select the Pocket Computer again, the game crashes giving me that report. For me it sounds like, there is data missing after the teleport so he cant render the item in the hand in the correct way.

I play All the Mods 9 in the version 0.2.55

If you need a more detailed report, i will try to get it. But I think, it should be possible to catch the issue with checking the array size or by storing the data required in a more stable way.

Crash Report:
Unreported exception thrown!
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at TRANSFORMER/computercraft@1.110.1/dan200.computercraft.core.terminal.Terminal.getBackgroundColourLine(Terminal.java:249)
	at TRANSFORMER/computercraft@1.110.1/dan200.computercraft.client.render.text.FixedWidthFontRenderer.drawTerminalBackground(FixedWidthFontRenderer.java:153)
	at TRANSFORMER/computercraft@1.110.1/dan200.computercraft.client.render.text.FixedWidthFontRenderer.drawTerminal(FixedWidthFontRenderer.java:191)
	at TRANSFORMER/computercraft@1.110.1/dan200.computercraft.client.render.PocketItemRenderer.renderItem(PocketItemRenderer.java:77)
	at TRANSFORMER/computercraft@1.110.1/dan200.computercraft.client.render.ItemMapLikeRenderer.renderItemFirstPersonCenter(ItemMapLikeRenderer.java:134)
	at TRANSFORMER/computercraft@1.110.1/dan200.computercraft.client.render.ItemMapLikeRenderer.renderItemFirstPerson(ItemMapLikeRenderer.java:42)
	at TRANSFORMER/computercraft@1.110.1/dan200.computercraft.client.ClientHooks.onRenderHeldItem(ClientHooks.java:80)
	at TRANSFORMER/computercraft@1.110.1/dan200.computercraft.client.ForgeClientHooks.onRenderInHand(ForgeClientHooks.java:57)
	at TRANSFORMER/computercraft@1.110.1/dan200.computercraft.client.__ForgeClientHooks_onRenderInHand_RenderHandEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@47.2.20/net.minecraftforge.client.ForgeHooksClient.renderSpecificFirstPersonHand(ForgeHooksClient.java:301)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.ItemInHandRenderer.m_109314_(ItemInHandRenderer.java:316)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.GameRenderer.redirect$bgh000$iris$disableVanillaHandRendering(GameRenderer.java:2632)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.GameRenderer.m_109120_(GameRenderer.java:852)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1132)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:909)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.main.Main.main(Main.java:218)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)

**Comment by AlmightyAnubis** [comment]
I tried shutting down the Pocket Computer before going the the gate, so there is nothing written on it. But it still crashed. It didn't happen some versions before, so there was something that changed.

**Comment by SquidDev** [comment]
Thanks for the report! This appears to be the same issue as #1765 — it should be fixed by updating to 1.110.2!
