### ISSUE TITLE
```IllegalStateException``` while running cloudcatcher and TLCO

### ISSUE THREAD

**Issue by powerboat9** [SquidDev-CC/CC-Tweaked#1803]
### Minecraft Version

1.20.x

### Version

1.110.1

### Details

![2024-04-23_18 48 20](https://github.com/cc-tweaked/CC-Tweaked/assets/7397652/c9d838eb-8bba-4fac-967f-4a4048d5bd98)

This happened while I was AFK on switchcraft. The following files may be relevant:

[cloud.lua](https://p.sc3.io/Yjd6gpKCNF)
[startup.lua](https://p.sc3.io/HZFaCUUDc9)
[prep.lua](https://p.sc3.io/U9nHWQjCzn)
[lib/homura.lua](https://p.sc3.io/W3nY7qDhgA)
[lib/hub.lua](https://p.sc3.io/Wg6Ffd9d3X)

**Comment by SquidDev** [comment]
I suspect this is just an internal netty error, but we should do a better job of what error we expose to the user.

**Comment by powerboat9** [comment]
Internal netty error?

**Comment by SquidDev** [comment]
Ahh, managed to get the logs. No, this is a thread-safety issue with multiple classes using the `CharsetDecoder`. Hadn't properly registered that these are not thread-safe. This should be easy to fix!

```
java.lang.IllegalStateException: Current state = RESET, new state = FLUSHED
        at java.nio.charset.CharsetDecoder.throwIllegalStateException(Unknown Source) ~[?:?]
        at java.nio.charset.CharsetDecoder.flush(Unknown Source) ~[?:?]
        at java.nio.charset.CharsetDecoder.decode(Unknown Source) ~[?:?]
        at dan200.computercraft.core.apis.http.websocket.WebsocketHandle.send(WebsocketHandle.java:90) ~[cc-tweaked-1.20.1-fabric-1.109.2.jar:?]
        at dan200.computercraft.core.asm.LuaMethodSupplier.lambda$static$0(LuaMethodSupplier.java:27) ~[cc-tweaked-1.20.1-fabric-1.109.2.jar:?]
        at dan200.computercraft.core.lua.BasicFunction.invoke(BasicFunction.java:45) ~[cc-tweaked-1.20.1-fabric-1.109.2.jar:?]
        at org.squiddev.cobalt.function.VarArgFunction.call(VarArgFunction.java:60) ~[cc_tweaked_cobalt-0.8.1-5f38dd5922b07ad.jar:?]
```
