### ISSUE TITLE
1.14 game crash, 1.13.2 wireless modems not detected and 1.12.2 block update states

### ISSUE THREAD

**Issue by abaddonsabyss** [SquidDev-CC/CC-Tweaked#191]
**MC 1.14
MC 1.13.2
&
MC 1.12.2**

**1.13.2**
wireless modems attach but computers cannot detect that its even there.
no peripherals attached or everything but wireless modems attached. tried opening wrapping and nothin.

**1.12.2**
so my resolution was i went back to older version because i wanted to use this feature.
i achieved my goal for the most part but also seen in YouTube videos and experienced for myself.
when changing output for redstone to on or even changing colours and text on monitors it need a block update to apply like breaking a sand block for the rest to fall. 
to allow it to turn on my redstone i had to break it and place again and same when turning off. major inconvenience when the idea was to some degree automate it.

**1.14**
attempted to use in 1.14 but game crashes with the later fabric installed.

**Comment by SquidDev** [comment]
Can you include your logs and mod versions? I'm fairly sure several of these bugs have been fixed at the latest version.

**Comment by abaddonsabyss** [comment]
Well i just got the latest version of 1.13.2 which has a fix for the the wireless modem and the 1.12.2 block updates. But i havent tested 1.14 again since earlier today. I tried the latest 1.14 version of cctweaked, the fabric mod loader worked fine but the moment i put the mod in it crashed. I will test again on the weekend and send u through the logs if you like? I havent used fabric  before ive just been using forge and honestly i just was writing few codes and dont mind not being on the latest mc version. Its a great mod. So great work man

**Comment by StefanJanssen95** [comment]
I've never used fabric before but it seems to be working with the _Mod Menu_ Mod

```[16:52:44] [main/INFO]: Loading for game Minecraft 1.14
[16:52:44] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
[16:52:50] [ForkJoinPool-1-worker-3/WARN]: Mod ID fabric uses outdated schema version: 0 < 1
[16:52:50] [main/INFO]: [FabricLoader] Loading 4 mods: modmenu@1.5.2-82, fabric@0.2.7+build.127, fabricloader@0.4.6+build.141, computercraft@${version}
[16:52:50] [main/WARN]: Mod `computercraft` (${version}) does not respect SemVer - comparison support is limited.
[16:52:50] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/C:/Users/MY_USER/Documents/mmc-stable-win32/MultiMC/libraries/net/fabricmc/sponge-mixin/0.7.11.30/sponge-mixin-0.7.11.30.jar Service=Knot/Fabric Env=CLIENT
[16:52:50] [main/INFO]: Compatibility level set to JAVA_8
[16:52:50] [main/WARN]: Mixin config computercraft.client.json does not specify "minVersion" property
[16:52:50] [main/WARN]: Mixin config net.fabricmc.fabric.mixins.client.json does not specify "minVersion" property
[16:52:50] [main/WARN]: Mixin config net.fabricmc.fabric.mixins.common.json does not specify "minVersion" property
[16:52:50] [main/WARN]: Mixin config mixins.modmenu.json does not specify "minVersion" property
[16:52:51] [main/WARN]: Error loading class: net/minecraft/client/render/FirstPersonRenderer (java.lang.ClassNotFoundException: net/minecraft/client/render/FirstPersonRenderer)
[16:52:51] [main/WARN]: @Mixin target net.minecraft.client.render.FirstPersonRenderer was not found computercraft.client.json:MixinFirstPersonRenderer
[16:52:51] [main/WARN]: Error loading class: net/minecraft/client/render/entity/ItemFrameEntityRenderer (java.lang.ClassNotFoundException: net/minecraft/client/render/entity/ItemFrameEntityRenderer)
[16:52:51] [main/WARN]: @Mixin target net.minecraft.client.render.entity.ItemFrameEntityRenderer was not found computercraft.client.json:MixinItemFrameEntityRenderer
[16:52:51] [main/WARN]: Error loading class: net/minecraft/client/MinecraftClient (java.lang.ClassNotFoundException: net/minecraft/client/MinecraftClient)
[16:52:51] [main/WARN]: @Mixin target net.minecraft.client.MinecraftClient was not found computercraft.client.json:MixinMinecraftGame
[16:52:51] [main/WARN]: Error loading class: net/minecraft/client/gui/Screen (java.lang.ClassNotFoundException: net/minecraft/client/gui/Screen)
[16:52:51] [main/WARN]: @Mixin target net.minecraft.client.gui.Screen was not found computercraft.client.json:MixinScreen
[16:52:51] [main/INFO]: Setting user: Codex404
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 5/4/19 4:52 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors!
	at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:45)
	at net.fabricmc.loader.entrypoint.hooks.EntrypointClient.start(EntrypointClient.java:34)
	at net.minecraft.class_310.method_1503(class_310.java)
	at net.minecraft.class_310.method_1514(class_310.java:395)
	at net.minecraft.client.main.Main.main(Main.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
	Suppressed: java.lang.NoClassDefFoundError: net/minecraft/util/registry/MutableRegistry
		at dan200.computercraft.ComputerCraft.onInitialize(ComputerCraft.java:198)
		at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.lambda$logErrors$0(EntrypointUtils.java:38)
		at java.util.ArrayList.forEach(Unknown Source)
		at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:36)
		... 19 more
	Caused by: java.lang.ClassNotFoundException: net.minecraft.util.registry.MutableRegistry
		at java.net.URLClassLoader.findClass(Unknown Source)
		at java.lang.ClassLoader.loadClass(Unknown Source)
		at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
		at java.lang.ClassLoader.loadClass(Unknown Source)
		at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:160)
		at java.lang.ClassLoader.loadClass(Unknown Source)
		... 23 more
```

```-- System Details --
Details:
	Minecraft Version: 1.14
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_112, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 568207360 bytes (541 MB) / 830472192 bytes (792 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
	Fabric Mods: 
		computercraft: ${version}
		fabric: 0.2.7+build.127
		fabricloader: 0.4.6+build.141
		modmenu: 1.5.2-82
```
When looking at this it seems that the version is not correctly loaded as it states ${version} where the other mods actually show a version.

**Comment by StefanJanssen95** [comment]
I just saw that the CurseForge page has a new version that the one listed under "releases" in this repo.
https://minecraft.curseforge.com/projects/cc-tweaked. 
with this version minecraft at least does not crash and ModMenu shows the CC-Tweaked as loaded.
