### ISSUE TITLE
java exception on getItemDetail

### ISSUE THREAD

**Issue by schindlershadow** [SquidDev-CC/CC-Tweaked#1988]
### Minecraft Version

1.21.x

### Version

cc-tweaked-1.21.1-forge-1.113.1

### Details

![Screenshot from 2024-10-03 21-03-13](https://github.com/user-attachments/assets/1e3c1718-dc71-4774-bda6-7a041c375f64)

server log
```
[21:05:13] [Server thread/ERROR] Attempted to load class net/minecraft/client/resources/language/I18n for invalid dist DEDICATED_SERVER
[21:05:13] [Server thread/ERROR] Error running task
```

**Comment by SquidDev** [comment]
Thanks for the report. This is most likely caused by another mod trying to use client classes on the dedicated server. Would you be able to attach you full log file? — there should be an exception following this message.

**Comment by schindlershadow** [comment]
sorry missed that part

seems to be forcecraft.items.flask.EntityFlaskItem.getName(EntityFlaskItem
```
[04Oct2024 09:36:53.018] [Server thread/ERROR] [net.neoforged.fml.common.asm.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/resources/language/I18n for invalid dist DEDICATED_SERVER
[04Oct2024 09:36:53.019] [Server thread/ERROR] [dan200.computercraft.core.computer.LuaContext/COMPUTER_ERROR.JAVA]: Error running task
java.lang.RuntimeException: Attempted to load class net/minecraft/client/resources/language/I18n for invalid dist DEDICATED_SERVER
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.common.asm.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:60) ~[loader-4.0.24.jar%2360!/:4.0]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:94) ~[modlauncher-11.0.4.jar%2362!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-11.0.4.jar%2362!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:57) ~[modlauncher-11.0.4.jar%2362!/:?]
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:190) ~[securejarhandler-3.0.8.jar:?]
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$20(ModuleClassLoader.java:298) ~[securejarhandler-3.0.8.jar:?]
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:311) ~[securejarhandler-3.0.8.jar:?]
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:298) ~[securejarhandler-3.0.8.jar:?]
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:214) ~[securejarhandler-3.0.8.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at TRANSFORMER/forcecraft@6.0.4/com.mrbysco.forcecraft.items.flask.EntityFlaskItem.getName(EntityFlaskItem.java:129) ~[forcecraft-1.21.1-6.0.4.jar%23459!/:6.0.4]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.item.ItemStack.getHoverName(ItemStack.java:737) ~[server-1.21.1-20240808.144430-srg.jar%23370!/:?]
	at TRANSFORMER/computercraft@1.113.1/dan200.computercraft.shared.details.ItemDetails.fill(ItemDetails.java:40) ~[cc-tweaked-1.21.1-forge-1.113.1.jar%23406!/:1.113.1]
	at TRANSFORMER/computercraft@1.113.1/dan200.computercraft.impl.detail.DetailRegistryImpl.getDetails(DetailRegistryImpl.java:46) ~[cc-tweaked-1.21.1-forge-1.113.1.jar%23406!/:1.113.1]
	at TRANSFORMER/computercraft@1.113.1/dan200.computercraft.shared.peripheral.generic.methods.InventoryMethods.getItemDetail(InventoryMethods.java:58) ~[cc-tweaked-1.21.1-forge-1.113.1.jar%23406!/:1.113.1]
	at TRANSFORMER/computercraft@1.113.1/dan200.computercraft.core.asm.PeripheralMethodSupplier.lambda$static$0(PeripheralMethodSupplier.java:28) ~[cc-tweaked-1.21.1-forge-1.113.1.jar%23406!/:1.113.1]
	at TRANSFORMER/computercraft@1.113.1/dan200.computercraft.core.asm.PeripheralMethodSupplier.lambda$static$2(PeripheralMethodSupplier.java:35) ~[cc-tweaked-1.21.1-forge-1.113.1.jar%23406!/:1.113.1]
	at TRANSFORMER/computercraft@1.113.1/dan200.computercraft.api.lua.TaskCallback.execute(TaskCallback.java:30) ~[cc-tweaked-1.21.1-forge-1.113.1.jar%23406!/:1.113.1]
	at TRANSFORMER/computercraft@1.113.1/dan200.computercraft.core.computer.GuardedLuaContext.lambda$issueMainThreadTask$0(GuardedLuaContext.java:45) ~[cc-tweaked-1.21.1-forge-1.113.1.jar%23406!/:1.113.1]
	at TRANSFORMER/computercraft@1.113.1/dan200.computercraft.core.computer.GuardedLuaContext.lambda$issueMainThreadTask$0(GuardedLuaContext.java:45) ~[cc-tweaked-1.21.1-forge-1.113.1.jar%23406!/:1.113.1]
	at TRANSFORMER/computercraft@1.113.1/dan200.computercraft.core.computer.GuardedLuaContext.lambda$issueMainThreadTask$0(GuardedLuaContext.java:45) ~[cc-tweaked-1.21.1-forge-1.113.1.jar%23406!/:1.113.1]
	at TRANSFORMER/computercraft@1.113.1/dan200.computercraft.core.computer.LuaContext.lambda$issueMainThreadTask$0(LuaContext.java:29) ~[cc-tweaked-1.21.1-forge-1.113.1.jar%23406!/:1.113.1]
	at TRANSFORMER/computercraft@1.113.1/dan200.computercraft.core.computer.mainthread.MainThreadExecutor.execute(MainThreadExecutor.java:138) ~[cc-tweaked-1.21.1-forge-1.113.1.jar%23406!/:1.113.1]
	at TRANSFORMER/computercraft@1.113.1/dan200.computercraft.core.computer.mainthread.MainThread.tick(MainThread.java:139) ~[cc-tweaked-1.21.1-forge-1.113.1.jar%23406!/:1.113.1]
	at TRANSFORMER/computercraft@1.113.1/dan200.computercraft.shared.computer.core.ServerContext.tick(ServerContext.java:154) ~[cc-tweaked-1.21.1-forge-1.113.1.jar%23406!/:1.113.1]
	at TRANSFORMER/computercraft@1.113.1/dan200.computercraft.shared.CommonHooks.onServerTickStart(CommonHooks.java:57) ~[cc-tweaked-1.21.1-forge-1.113.1.jar%23406!/:1.113.1]
	at TRANSFORMER/computercraft@1.113.1/dan200.computercraft.shared.ForgeCommonHooks.onServerTick(ForgeCommonHooks.java:38) ~[cc-tweaked-1.21.1-forge-1.113.1.jar%23406!/:1.113.1]
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350) ~[bus-8.0.1.jar%2367!/:?]
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:315) ~[bus-8.0.1.jar%2367!/:?]
	at TRANSFORMER/neoforge@21.1.42/net.neoforged.neoforge.event.EventHooks.fireServerTickPre(EventHooks.java:992) ~[neoforge-21.1.42-universal.jar%23371!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:915) ~[server-1.21.1-20240808.144430-srg.jar%23370!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:707) ~[server-1.21.1-20240808.144430-srg.jar%23370!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267) ~[server-1.21.1-20240808.144430-srg.jar%23370!/:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

**Comment by schindlershadow** [comment]
item data on that flask from forcecraft
```
{
  count: 1,
  Slot: 6b,
  components:
    {
      "forcecraft:flask_content":
        {
          storedType: "minecraft:villager",
          entityData:
            {
              Brain: { memories: {} },
              "neoforge:attachments": { "piglinproliferation:critical": 0b },
              HurtByTimestamp: 0,
              FoodLevel: 0b,
              Invulnerable: 0b,
              FallFlying: 0b,
              ForcedAge: 0,
              Gossips:
                [
                  {
                    Target:
                      [I; 1243519230, 2012106721, -1099018850, -1235494497],
                    Type: "major_positive",
                    Value: 20,
                  },
                  {
                    Target:
                      [I; 1243519230, 2012106721, -1099018850, -1235494497],
                    Type: "minor_positive",
                    Value: 25,
                  },
                ],
              PortalCooldown: 0,
              AbsorptionAmount: 0.0f,
              LastRestock: 0L,
              FallDistance: 0.0f,
              DeathTime: 0s,
              Xp: 0,
              LastGossipDecay: 18196681L,
              HandDropChances: [0.085f, 0.085f],
              PersistenceRequired: 1b,
              UUID: [I; 827542961, 776225802, -1781811966, -950618387],
              NeoForgeData: {},
              Tags: ["collective.checked", "villagernames.named"],
              Age: 0,
              Motion: [0.0d, -0.0784000015258789d, 0.0d],
              PURESUFFERINGHyperCharge: 0,
              za_data: {},
              Health: 20.0f,
              LeftHanded: 0b,
              Air: 300s,
              OnGround: 1b,
              Rotation: [192.69531f, 5.8828278f],
              HandItems: [{}, {}],
              RestocksToday: 0,
              ArmorDropChances: [0.085f, 0.085f, 0.085f, 0.085f],
              "neoforge:spawn_type": "STRUCTURE",
              CustomName: '"Kandi"',
              Pos: [-17304.41520218819d, 91.0d, -9399.869747887145d],
              Fire: -1s,
              ArmorItems: [{}, {}, {}, {}],
              CanPickUpLoot: 1b,
              VillagerData:
                {
                  profession: "minecraft:none",
                  level: 1,
                  type: "minecraft:plains",
                },
              attributes:
                [
                  { id: "minecraft:generic.movement_speed", base: 0.5d },
                  { id: "minecraft:generic.oxygen_bonus", base: 0.0d },
                  { id: "caelus:fall_flying", base: 0.1d },
                  {
                    id: "minecraft:generic.scale",
                    modifiers:
                      [
                        {
                          amount: -0.08111347170394252d,
                          id: "natural_size_variation:size_variation",
                          operation: "add_value",
                        },
                      ],
                    base: 1.0d,
                  },
                  {
                    id: "minecraft:generic.follow_range",
                    modifiers:
                      [
                        {
                          amount: 0.07476586479090724d,
                          id: "minecraft:random_spawn_bonus",
                          operation: "add_multiplied_base",
                        },
                      ],
                    base: 48.0d,
                  },
                  { id: "minecraft:generic.step_height", base: 0.6d },
                  { id: "minecraft:generic.gravity", base: 0.08d },
                ],
              HurtTime: 0s,
              Inventory: [],
            },
        },
    },
  id: "forcecraft:villager_flask",
}
```

**Comment by SquidDev** [comment]
Yep, this appears to be an issue with ForceCraft, specifically [this line](https://github.com/Mrbysco/ForceCraft/blob/0e54173907ade34aa78811dbf3bf81e9aeacfc28/src/main/java/com/mrbysco/forcecraft/items/flask/EntityFlaskItem.java#L129). Can you report this to them?

The fix here should be quite simple, one just needs to replace the usage of `I18n` with another `Component.translatable`:

```diff
- return Component.translatable(super.getDescriptionId(stack), I18n.get(mobTranslation));
+ return Component.translatable(super.getDescriptionId(stack), Component.translatable(mobTranslation));
