### ISSUE TITLE
SteamPunk LPS - Crash

### ISSUE THREAD

**Issue by Kroseida** [SquidDev-CC/CC-Tweaked#2031]
### Minecraft Version

1.20.1

### Version

1.20.1-forge-1.113.1

### Details

Hey. 

The Server is crashing based on computer craft.
I guess currently is only one turttle used for mining.
Running on dedicated vanilla/forge Server Ryzen 8600G with 16gb of RAM on a Linux Ubuntu Machine.
The server is assigned with ~12gb of RAM, swap disabled.

`
[17:46:28] [ComputerCraft-Computer-Worker-0/ERROR] [da.co.co.co.co.ComputerThread/]: Error running task on computer #1
java.lang.InterruptedException: null
        at java.util.concurrent.locks.ReentrantLock$Sync.lockInterruptibly(ReentrantLock.java:159) ~[?:?] {}
        at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:372) ~[?:?] {re:mixin}
        at dan200.computercraft.core.computer.ComputerExecutor.shutdown(ComputerExecutor.java:421) ~[cc-tweaked-1.20.1-forge-1.113.1.jar%23416!/:1.113.1] {re:classloading}
        at dan200.computercraft.core.computer.ComputerExecutor.workImpl(ComputerExecutor.java:497) ~[cc-tweaked-1.20.1-forge-1.113.1.jar%23416!/:1.113.1] {re:classloading}
        at dan200.computercraft.core.computer.ComputerExecutor.work(ComputerExecutor.java:461) ~[cc-tweaked-1.20.1-forge-1.113.1.jar%23416!/:1.113.1] {re:classloading}
        at dan200.computercraft.core.computer.computerthread.ComputerThread$WorkerThread.runImpl(ComputerThread.java:660) ~[cc-tweaked-1.20.1-forge-1.113.1.jar%23416!/:1.113.1] {re:classloading}
        at dan200.computercraft.core.computer.computerthread.ComputerThread$WorkerThread.run(ComputerThread.java:614) ~[cc-tweaked-1.20.1-forge-1.113.1.jar%23416!/:1.113.1] {re:classloading}
        at java.lang.Thread.run(Thread.java:840) ~[?:?] {re:mixin}
`

**Comment by SquidDev** [comment]
Thanks for the report! Can you post the full log? This error on its own shouldn't be enough to crash the server.

**Comment by Kroseida** [comment]
Its a little bit difficult. We are playing with about 15 - 25 players on this server, so I would not pref. sending the entire log in github. I can send it to you privately.
Thanks for help!

**Comment by SquidDev** [comment]
@Kroseida Did you have any luck finding the log?
