### ISSUE TITLE
Crash on a Forge 1.14.2 dedicated server

### ISSUE THREAD

**Issue by SquidDev** [SquidDev-CC/CC-Tweaked#255]
## Useful information to include:
 - Minecraft version: 1.14.2
 - CC: Tweaked version: 1.83.1

Launch a dedicated server and right click a computer (most likely any tile entity). You should receive the following crash:

```
java.lang.NoSuchMethodError: net.minecraft.block.Block.func_200291_n()Lnet/minecraft/util/text/ITextComponent;
    at dan200.computercraft.shared.computer.blocks.TileComputerBase.func_200200_C_(TileComputerBase.java:416) ~[?:1.83.1] {}
    at net.minecraft.util.INameable.func_145748_c_(SourceFile:15) ~[?:?] {}
    at dan200.computercraft.shared.computer.blocks.TileComputerBase.func_145748_c_(TileComputerBase.java:436) ~[?:1.83.1] {}
    at net.minecraftforge.fml.network.NetworkHooks.openGui(NetworkHooks.java:167) ~[?:?] {}
    at dan200.computercraft.shared.network.container.ContainerData.open(ContainerData.java:33) ~[?:1.83.1] {}
    at dan200.computercraft.shared.computer.blocks.TileComputerBase.onActivate(TileComputerBase.java:125) ~[?:1.83.1] {}
    at dan200.computercraft.shared.common.BlockGeneric.func_220051_a(BlockGeneric.java:54) ~[?:1.83.1] {}
```

([full report](https://pastebin.com/Bh92YYHV))

I _really_ should have tested this first. Go me.

**Comment by UmutAlihan** [comment]
Hi,

I have the same crash:
My crash report is below. I hope it helps:


---- Minecraft Crash Report ----
// Don't do that.

Time: 6/16/19 11:34 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.block.Block.func_200291_n()Lnet/minecraft/util/text/ITextComponent;
        at dan200.computercraft.shared.computer.blocks.TileComputerBase.func_200200_C_(TileComputerBase.java:416) ~[?:1.83.1] {}
        at net.minecraft.util.INameable.func_145748_c_(SourceFile:15) ~[?:?] {}
        at dan200.computercraft.shared.computer.blocks.TileComputerBase.func_145748_c_(TileComputerBase.java:436) ~[?:1.83.1] {}
        at net.minecraftforge.fml.network.NetworkHooks.openGui(NetworkHooks.java:167) ~[?:?] {}
        at dan200.computercraft.shared.network.container.ContainerData.open(ContainerData.java:33) ~[?:1.83.1] {}
        at dan200.computercraft.shared.computer.blocks.TileComputerBase.onActivate(TileComputerBase.java:125) ~[?:1.83.1] {}
        at dan200.computercraft.shared.turtle.blocks.TileTurtle.onActivate(TileTurtle.java:220) ~[?:1.83.1] {}
        at dan200.computercraft.shared.common.BlockGeneric.func_220051_a(BlockGeneric.java:54) ~[?:1.83.1] {}
        at net.minecraft.block.BlockState.func_215687_a(BlockState.java:275) ~[?:?] {pl:runtimedistcleaner:A}
        at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:347) ~[?:?] {}
        at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:875) ~[?:?] {}
        at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36) ~[?:?] {}
        at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10) ~[?:?] {}
        at net.minecraft.network.PacketThreadUtil.func_210405_a(SourceFile:15) ~[?:?] {}
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:135) ~[?:?] {pl:accesstransformer:B}
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:114) ~[?:?] {pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:683) ~[?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:677) ~[?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:123) ~[?:?] {pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:663) ~[?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
        Minecraft Version: 1.14.2
        Operating System: Linux (amd64) version 4.15.0-51-generic
        Java Version: 1.8.0_212, Oracle Corporation
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 542638888 bytes (517 MB) / 1060110336 bytes (1011 MB) up to 1431830528 bytes (1365 MB)
        JVM Flags: 2 total; -Xms1024M -Xmx1536M
        FML: New FML!
        Loaded coremods (and transformers): Nothing
        Player Count: 1 / 20; [ServerPlayerEntity['averneus'/163, l='world', x=-333.09, y=69.00, z=-96.82]]
        Data Packs: mod:computercraft, mod:forge, vanilla
        Is Modded: Definitely; Server brand changed to 'forge'
        Type: Dedicated Server (map_server.txt)


Below is the Exception caught in server logs:
[16Jun2019 23:34:28.231] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
java.lang.NoSuchMethodError: net.minecraft.block.Block.func_200291_n()Lnet/minecraft/util/text/ITextComponent;
        at dan200.computercraft.shared.computer.blocks.TileComputerBase.func_200200_C_(TileComputerBase.java:416) ~[?:1.83.1]
        at net.minecraft.util.INameable.func_145748_c_(SourceFile:15) ~[?:?]
        at dan200.computercraft.shared.computer.blocks.TileComputerBase.func_145748_c_(TileComputerBase.java:436) ~[?:1.83.1]
        at net.minecraftforge.fml.network.NetworkHooks.openGui(NetworkHooks.java:167) ~[?:?]
        at dan200.computercraft.shared.network.container.ContainerData.open(ContainerData.java:33) ~[?:1.83.1]
        at dan200.computercraft.shared.computer.blocks.TileComputerBase.onActivate(TileComputerBase.java:125) ~[?:1.83.1]
        at dan200.computercraft.shared.turtle.blocks.TileTurtle.onActivate(TileTurtle.java:220) ~[?:1.83.1]
        at dan200.computercraft.shared.common.BlockGeneric.func_220051_a(BlockGeneric.java:54) ~[?:1.83.1]
        at net.minecraft.block.BlockState.func_215687_a(BlockState.java:275) ~[?:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:347) ~[?:?]
        at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:875) ~[?:?]
        at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36) ~[?:?]
        at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10) ~[?:?]
        at net.minecraft.network.PacketThreadUtil.func_210405_a(SourceFile:15) ~[?:?]
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:135) ~[?:?]
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:683) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:677) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:123) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:663) ~[?:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]


And while I turn on the server I get these warnings below:

[16Jun2019 23:27:02.744] [modloading-worker-1/INFO] [net.minecraftforge.common.MinecraftForge/FORGE]: MinecraftForge v26.0.32 Initialized
[16Jun2019 23:27:03.295] [Server thread/WARN] [computercraft/]: No data fixer registered for block entity computercraft:computer_normal
[16Jun2019 23:27:03.296] [Server thread/WARN] [computercraft/]: No data fixer registered for block entity computercraft:computer_advanced
[16Jun2019 23:27:03.300] [Server thread/WARN] [computercraft/]: No data fixer registered for block entity computercraft:command_computer
[16Jun2019 23:27:03.307] [Server thread/WARN] [computercraft/]: No data fixer registered for block entity computercraft:turtle_normal
[16Jun2019 23:27:03.309] [Server thread/WARN] [computercraft/]: No data fixer registered for block entity computercraft:turtle_advanced
[16Jun2019 23:27:03.319] [Server thread/WARN] [computercraft/]: No data fixer registered for block entity computercraft:speaker
[16Jun2019 23:27:03.332] [Server thread/WARN] [computercraft/]: No data fixer registered for block entity computercraft:disk_drive
[16Jun2019 23:27:03.349] [Server thread/WARN] [computercraft/]: No data fixer registered for block entity computercraft:monitor_normal
[16Jun2019 23:27:03.351] [Server thread/WARN] [computercraft/]: No data fixer registered for block entity computercraft:monitor_advanced
[16Jun2019 23:27:03.394] [Server thread/WARN] [computercraft/]: No data fixer registered for block entity computercraft:printer
[16Jun2019 23:27:03.405] [Server thread/WARN] [computercraft/]: No data fixer registered for block entity computercraft:wireless_modem_normal
[16Jun2019 23:27:03.408] [Server thread/WARN] [computercraft/]: No data fixer registered for block entity computercraft:wireless_modem_advanced
[16Jun2019 23:27:03.453] [Server thread/WARN] [computercraft/]: No data fixer registered for block entity computercraft:wired_modem_full
[16Jun2019 23:27:03.464] [Server thread/WARN] [computercraft/]: No data fixer registered for block entity computercraft:cable



Anyway thank you very much for your commitment to keep updated this mod. You are the hero of one of us here in the community. It is very much appreciated. May the karma provide you the bests of bests :)

Cheers,

**Comment by ethanxxxl** [comment]
I am also having this issue:

---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 6/20/19 5:02 AM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.block.Block.func_200291_n()Lnet/minecraft/util/text/ITextComponent;
	at dan200.computercraft.shared.computer.blocks.TileComputerBase.func_200200_C_(TileComputerBase.java:416) ~[?:1.83.1] {}
	at net.minecraft.util.INameable.func_145748_c_(SourceFile:15) ~[?:?] {}
	at dan200.computercraft.shared.computer.blocks.TileComputerBase.func_145748_c_(TileComputerBase.java:436) ~[?:1.83.1] {}
	at net.minecraftforge.fml.network.NetworkHooks.openGui(NetworkHooks.java:167) ~[?:?] {}
	at dan200.computercraft.shared.network.container.ContainerData.open(ContainerData.java:33) ~[?:1.83.1] {}
	at dan200.computercraft.shared.computer.blocks.TileComputerBase.onActivate(TileComputerBase.java:125) ~[?:1.83.1] {}
	at dan200.computercraft.shared.common.BlockGeneric.func_220051_a(BlockGeneric.java:54) ~[?:1.83.1] {}
	at net.minecraft.block.BlockState.func_215687_a(BlockState.java:275) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:347) ~[?:?] {}
	at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:875) ~[?:?] {}
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36) ~[?:?] {}
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10) ~[?:?] {}
	at net.minecraft.network.PacketThreadUtil.func_210405_a(SourceFile:15) ~[?:?] {}
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:135) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:114) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:683) ~[?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:677) ~[?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:123) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:663) ~[?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211] {}


A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
	Minecraft Version: 1.14.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2909289088 bytes (2774 MB) / 4141350912 bytes (3949 MB) up to 4141350912 bytes (3949 MB)
	JVM Flags: 2 total; -Xmx4096M -Xms4096M
	FML: New FML!
	Loaded coremods (and transformers): Nothing
	Player Count: 1 / 20; [ServerPlayerEntity['ethanxxxl'/193, l='world', x=-55.63, y=63.00, z=224.32]]
	Data Packs: mod:forge, mod:computercraft, vanilla
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)


hopefully this is helpful. this is the first time in a while that I have looked at any think Minecraft related. I was pleasantly surprised to see that there was an up-to-date version of one of my favorite mods. You seem to be very dedicated to this, and its awesome. keep it up!

**Comment by ethanxxxl** [comment]
I am also having this issue:

---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 6/20/19 5:02 AM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.block.Block.func_200291_n()Lnet/minecraft/util/text/ITextComponent;
	at dan200.computercraft.shared.computer.blocks.TileComputerBase.func_200200_C_(TileComputerBase.java:416) ~[?:1.83.1] {}
	at net.minecraft.util.INameable.func_145748_c_(SourceFile:15) ~[?:?] {}
	at dan200.computercraft.shared.computer.blocks.TileComputerBase.func_145748_c_(TileComputerBase.java:436) ~[?:1.83.1] {}
	at net.minecraftforge.fml.network.NetworkHooks.openGui(NetworkHooks.java:167) ~[?:?] {}
	at dan200.computercraft.shared.network.container.ContainerData.open(ContainerData.java:33) ~[?:1.83.1] {}
	at dan200.computercraft.shared.computer.blocks.TileComputerBase.onActivate(TileComputerBase.java:125) ~[?:1.83.1] {}
	at dan200.computercraft.shared.common.BlockGeneric.func_220051_a(BlockGeneric.java:54) ~[?:1.83.1] {}
	at net.minecraft.block.BlockState.func_215687_a(BlockState.java:275) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:347) ~[?:?] {}
	at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:875) ~[?:?] {}
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36) ~[?:?] {}
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10) ~[?:?] {}
	at net.minecraft.network.PacketThreadUtil.func_210405_a(SourceFile:15) ~[?:?] {}
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:135) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:114) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:683) ~[?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:677) ~[?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:123) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:663) ~[?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211] {}


A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
	Minecraft Version: 1.14.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2909289088 bytes (2774 MB) / 4141350912 bytes (3949 MB) up to 4141350912 bytes (3949 MB)
	JVM Flags: 2 total; -Xmx4096M -Xms4096M
	FML: New FML!
	Loaded coremods (and transformers): Nothing
	Player Count: 1 / 20; [ServerPlayerEntity['ethanxxxl'/193, l='world', x=-55.63, y=63.00, z=224.32]]
	Data Packs: mod:forge, mod:computercraft, vanilla
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)


hopefully this is helpful. this is the first time in a while that I have looked at any think Minecraft related. I was pleasantly surprised to see that there was an up-to-date version of one of my favorite mods. You seem to be very dedicated to this, and its awesome. keep it up!

**Comment by ethanxxxl** [comment]
I am also having this issue:

---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 6/20/19 5:02 AM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.block.Block.func_200291_n()Lnet/minecraft/util/text/ITextComponent;
	at dan200.computercraft.shared.computer.blocks.TileComputerBase.func_200200_C_(TileComputerBase.java:416) ~[?:1.83.1] {}
	at net.minecraft.util.INameable.func_145748_c_(SourceFile:15) ~[?:?] {}
	at dan200.computercraft.shared.computer.blocks.TileComputerBase.func_145748_c_(TileComputerBase.java:436) ~[?:1.83.1] {}
	at net.minecraftforge.fml.network.NetworkHooks.openGui(NetworkHooks.java:167) ~[?:?] {}
	at dan200.computercraft.shared.network.container.ContainerData.open(ContainerData.java:33) ~[?:1.83.1] {}
	at dan200.computercraft.shared.computer.blocks.TileComputerBase.onActivate(TileComputerBase.java:125) ~[?:1.83.1] {}
	at dan200.computercraft.shared.common.BlockGeneric.func_220051_a(BlockGeneric.java:54) ~[?:1.83.1] {}
	at net.minecraft.block.BlockState.func_215687_a(BlockState.java:275) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:347) ~[?:?] {}
	at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:875) ~[?:?] {}
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36) ~[?:?] {}
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10) ~[?:?] {}
	at net.minecraft.network.PacketThreadUtil.func_210405_a(SourceFile:15) ~[?:?] {}
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:135) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:114) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:683) ~[?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:677) ~[?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:123) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:663) ~[?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211] {}


A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
	Minecraft Version: 1.14.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2909289088 bytes (2774 MB) / 4141350912 bytes (3949 MB) up to 4141350912 bytes (3949 MB)
	JVM Flags: 2 total; -Xmx4096M -Xms4096M
	FML: New FML!
	Loaded coremods (and transformers): Nothing
	Player Count: 1 / 20; [ServerPlayerEntity['ethanxxxl'/193, l='world', x=-55.63, y=63.00, z=224.32]]
	Data Packs: mod:forge, mod:computercraft, vanilla
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)


hopefully this is helpful. this is the first time in a while that I have looked at any think Minecraft related. I was pleasantly surprised to see that there was an up-to-date version of one of my favorite mods. You seem to be very dedicated to this, and its awesome. keep it up!

**Comment by lupus590** [comment]
It would be nice if people put their crash logs in spoiler tags or uploaded them to pastebin like services
