### ISSUE TITLE
Crash with turtles

### ISSUE THREAD

**Issue by SquidDev** [SquidDev-CC/CC-Tweaked#301]
## Useful information to include:
 - Minecraft version: 1.14.4
 - CC: Tweaked version: 1.84.1
 - Detailed reproduction steps: No clue - just yoinked this from a comment on CurseForge.

<details>
<summary>Crash log</summary>

```
java.lang.IllegalArgumentException: Cannot get property DirectionProperty{name=facing, clazz=class net.minecraft.util.Direction, values=[north, south, west, east]} as it does not exist in Block{minecraft:air}
    at net.minecraft.state.StateHolder.func_177229_b(SourceFile:95) ~[?:?] {pl:accesstransformer:B}
    at dan200.computercraft.shared.turtle.blocks.TileTurtle.getDirection(TileTurtle.java:332) ~[?:1.84.1] {}
    at dan200.computercraft.shared.computer.blocks.TileComputerBase.remapToLocalSide(TileComputerBase.java:211) ~[?:1.84.1] {}
    at dan200.computercraft.shared.computer.blocks.TileComputerBase.updateSideInput(TileComputerBase.java:222) ~[?:1.84.1] {}
    at dan200.computercraft.shared.computer.blocks.TileComputerBase.updateInput(TileComputerBase.java:263) ~[?:1.84.1] {}
    at dan200.computercraft.shared.computer.blocks.TileComputerBase.updateInput(TileComputerBase.java:286) ~[?:1.84.1] {}
    at dan200.computercraft.shared.computer.blocks.TileComputerBase.onNeighbourTileEntityChange(TileComputerBase.java:142) ~[?:1.84.1] {}
    at dan200.computercraft.shared.turtle.blocks.TileTurtle.onNeighbourTileEntityChange(TileTurtle.java:259) ~[?:1.84.1] {}
    at dan200.computercraft.shared.common.BlockGeneric.onNeighborChange(BlockGeneric.java:69) ~[?:1.84.1] {}
    at net.minecraftforge.common.extensions.IForgeBlockState.onNeighborChange(IForgeBlockState.java:566) ~[?:?] {pl:runtimedistcleaner:A}
    at net.minecraft.world.World.func_175666_e(World.java:1302) ~[?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
    at net.minecraft.tileentity.TileEntity.func_70296_d(TileEntity.java:104) ~[?:?] {pl:runtimedistcleaner:A}
    at dan200.computercraft.shared.turtle.blocks.TileTurtle.func_70296_d(TileTurtle.java:477) ~[?:1.84.1] {}
    at dan200.computercraft.shared.common.TileGeneric.updateBlock(TileGeneric.java:35) ~[?:1.84.1] {}
    at dan200.computercraft.shared.computer.blocks.TileComputerBase.createServerComputer(TileComputerBase.java:362) ~[?:1.84.1] {}
    at dan200.computercraft.shared.computer.blocks.TileComputerBase.func_73660_a(TileComputerBase.java:150) ~[?:1.84.1] {}
    at dan200.computercraft.shared.turtle.blocks.TileTurtle.func_73660_a(TileTurtle.java:230) ~[?:1.84.1] {}
    at net.minecraft.world.World.func_217391_K(World.java:621) ~[?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
    at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:367) ~[?:?] {pl:runtimedistcleaner:A}
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:829) ~[?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:324) ~[?:?] {pl:accesstransformer:B}
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764) ~[?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_221] {}
```

[Full log on Pastebin](https://pastebin.com/3sf40bGS)

</details>

**Comment by SquidDev** [comment]
I'm going to flag this as invalid for now. I realise this is a bit cheeky, but I'm really not sure how this bug could occur. The TE methods are being called from the block state, which is in turn called from the world - this should mean the block and tile are in the correct position in the world.
