### ISSUE TITLE
[1.14.4] ticking block entity

### ISSUE THREAD

**Issue by olderscrolls** [SquidDev-CC/CC-Tweaked#306]
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2019.10.20. 19:14
Description: Ticking block entity

java.lang.NoSuchMethodError: net.minecraftforge.common.ForgeHooks.getBurnTime(Lnet/minecraft/item/ItemStack;)I
	at dan200.computercraft.shared.turtle.FurnaceRefuelHandler.getFuelPerItem(FurnaceRefuelHandler.java:56) ~[?:1.85.0] {}
	at dan200.computercraft.shared.turtle.FurnaceRefuelHandler.onTurtleRefuel(FurnaceRefuelHandler.java:62) ~[?:1.85.0] {}
	at net.minecraftforge.eventbus.ASMEventHandler_6_FurnaceRefuelHandler_onTurtleRefuel_TurtleRefuelEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
	at dan200.computercraft.shared.turtle.core.TurtleRefuelCommand.execute(TurtleRefuelCommand.java:37) ~[?:1.85.0] {}
	at dan200.computercraft.shared.turtle.core.TurtleBrain.updateCommands(TurtleBrain.java:796) ~[?:1.85.0] {}
	at dan200.computercraft.shared.turtle.core.TurtleBrain.update(TurtleBrain.java:141) ~[?:1.85.0] {}
	at dan200.computercraft.shared.turtle.blocks.TileTurtle.func_73660_a(TileTurtle.java:231) ~[?:1.85.0] {}
	at net.minecraft.world.World.func_217391_K(World.java:621) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:367) ~[?:?] {}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:829) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [?:?] {pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at dan200.computercraft.shared.turtle.FurnaceRefuelHandler.getFuelPerItem(FurnaceRefuelHandler.java:56)
	at dan200.computercraft.shared.turtle.FurnaceRefuelHandler.onTurtleRefuel(FurnaceRefuelHandler.java:62)
	at net.minecraftforge.eventbus.ASMEventHandler_6_FurnaceRefuelHandler_onTurtleRefuel_TurtleRefuelEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at dan200.computercraft.shared.turtle.core.TurtleRefuelCommand.execute(TurtleRefuelCommand.java:37)
	at dan200.computercraft.shared.turtle.core.TurtleBrain.updateCommands(TurtleBrain.java:796)
	at dan200.computercraft.shared.turtle.core.TurtleBrain.update(TurtleBrain.java:141)
	at dan200.computercraft.shared.turtle.blocks.TileTurtle.func_73660_a(TileTurtle.java:231)

-- Block entity being ticked --
Details:
	Name: computercraft:turtle_normal // dan200.computercraft.shared.turtle.blocks.TileTurtle
	Block: Block{computercraft:turtle_normal}[facing=west,waterlogged=false]
	Block location: World: (-172,67,246), Chunk: (at 4,4,6 in -11,15; contains blocks -176,0,240 to -161,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Block: Block{computercraft:turtle_normal}[facing=west,waterlogged=false]
	Block location: World: (-172,67,246), Chunk: (at 4,4,6 in -11,15; contains blocks -176,0,240 to -161,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Stacktrace:
	at net.minecraft.world.World.func_217391_K(World.java:621)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:367)

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['OlderScrolls'/286, l='New World', x=-172.88, y=67.00, z=245.28]]
	Chunk stats: ServerChunkCache: 6241
	Level dimension: DimensionType{minecraft:overworld}
	Level name: New World
	Level seed: 4756756511793311772
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: {}
	Level spawn location: World: (-176,68,240), Chunk: (at 0,4,0 in -11,15; contains blocks -176,0,240 to -161,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1874 game time, 1874 day time
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 144749 (now: false), thunder time: 120426 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:829)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 635786440 bytes (606 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 3.2.0+60+b86c1d4
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.1.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.1.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.0.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.1.0.jar fml TRANSFORMATIONSERVICE 
	FML: 28.1
	Forge: net.minecraftforge:28.1.0
	FML Language Providers: 
		javafml@28.1
		minecraft@1
	Mod List: 
		cc-tweaked-1.14.4-1.85.0.jar CC: Tweaked {computercraft@1.85.0 DONE}
		forge-1.14.4-28.1.0-universal.jar Forge {forge@28.1.0 DONE}
		forge-1.14.4-28.1.0-client.jar Minecraft {minecraft@1.14.4 DONE}
	Player Count: 1 / 8; [ServerPlayerEntity['OlderScrolls'/286, l='New World', x=-172.88, y=67.00, z=245.28]]
	Data Packs: vanilla, mod:forge, mod:computercraft
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by SquidDev** [comment]
Can you update to a version of Forge beyond 28.1.5 and try again? Sorry, I should have made that a hard dependency.
