### ISSUE TITLE
Game crash on 'refuel' command for turtle

### ISSUE THREAD

**Issue by jatoniekoKoSaL** [SquidDev-CC/CC-Tweaked#308]
## Useful information to include:
 - Minecraft version 1.14.4 (Forge 28.1.0)
 - CC: Tweaked version 1.85.0
 - Always on refuel...

`---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 21.10.19 22:31
Description: Ticking block entity

java.lang.NoSuchMethodError: net.minecraftforge.common.ForgeHooks.getBurnTime(Lnet/minecraft/item/ItemStack;)I
	at dan200.computercraft.shared.turtle.FurnaceRefuelHandler.getFuelPerItem(FurnaceRefuelHandler.java:56) ~[?:1.85.0] {}
	at dan200.computercraft.shared.turtle.FurnaceRefuelHandler.onTurtleRefuel(FurnaceRefuelHandler.java:62) ~[?:1.85.0] {}
	at net.minecraftforge.eventbus.ASMEventHandler_7_FurnaceRefuelHandler_onTurtleRefuel_TurtleRefuelEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
	at dan200.computercraft.shared.turtle.core.TurtleRefuelCommand.execute(TurtleRefuelCommand.java:37) ~[?:1.85.0] {}
	at dan200.computercraft.shared.turtle.core.TurtleBrain.updateCommands(TurtleBrain.java:796) ~[?:1.85.0] {}
	at dan200.computercraft.shared.turtle.core.TurtleBrain.update(TurtleBrain.java:141) ~[?:1.85.0] {}
	at dan200.computercraft.shared.turtle.blocks.TileTurtle.func_73660_a(TileTurtle.java:231) ~[?:1.85.0] {}
	at net.minecraft.world.World.func_217391_K(World.java:621) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:367) ~[?:?] {}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:829) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [?:?] {pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at dan200.computercraft.shared.turtle.FurnaceRefuelHandler.getFuelPerItem(FurnaceRefuelHandler.java:56)
	at dan200.computercraft.shared.turtle.FurnaceRefuelHandler.onTurtleRefuel(FurnaceRefuelHandler.java:62)
	at net.minecraftforge.eventbus.ASMEventHandler_7_FurnaceRefuelHandler_onTurtleRefuel_TurtleRefuelEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at dan200.computercraft.shared.turtle.core.TurtleRefuelCommand.execute(TurtleRefuelCommand.java:37)
	at dan200.computercraft.shared.turtle.core.TurtleBrain.updateCommands(TurtleBrain.java:796)
	at dan200.computercraft.shared.turtle.core.TurtleBrain.update(TurtleBrain.java:141)
	at dan200.computercraft.shared.turtle.blocks.TileTurtle.func_73660_a(TileTurtle.java:231)

-- Block entity being ticked --
Details:
	Name: computercraft:turtle_normal // dan200.computercraft.shared.turtle.blocks.TileTurtle
	Block: Block{computercraft:turtle_normal}[facing=east,waterlogged=false]
	Block location: World: (-319,15,228), Chunk: (at 1,0,4 in -20,14; contains blocks -320,0,224 to -305,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Block: Block{computercraft:turtle_normal}[facing=east,waterlogged=false]
	Block location: World: (-319,15,228), Chunk: (at 1,0,4 in -20,14; contains blocks -320,0,224 to -305,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Stacktrace:
	at net.minecraft.world.World.func_217391_K(World.java:621)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:367)
`

**Comment by jatoniekoKoSaL** [comment]
Thanks so much! That helped. :)
