### ISSUE TITLE
Crafty Turtle Froze the Game

### ISSUE THREAD

**Issue by WenXin20** [SquidDev-CC/CC-Tweaked#370]
## Useful information to include: 
 - `Minecraft v1.14.4`
 - `CC: Tweaked v1.86.2`
 - Detailed reproduction steps: In my Creative, single player world, I placed a Crafty Turtle and my game immediately froze. There was also a [Silent's Mechanisms](https://www.curseforge.com/minecraft/mc-mods/silents-mechanisms) Wire right next to where I had placed it, but I'm not sure its related. 
- [Full Log](https://gist.github.com/WenXin20/39e05339dfb16dc49e6afc525f6c61c1)
- Log Excerpt: 
```
[21:40:32] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: dan200/computercraft/shared/turtle/core/TurtleBrain
	at dan200.computercraft.shared.turtle.blocks.TileTurtle.<init>(TileTurtle.java:83) ~[?:1.86.2]
	at dan200.computercraft.shared.turtle.blocks.TileTurtle.lambda$static$0(TileTurtle.java:63) ~[?:1.86.2]
	at dan200.computercraft.shared.turtle.blocks.TileTurtle$$Lambda$7736/2083628294.apply(Unknown Source) ~[?:?]
	at dan200.computercraft.shared.util.NamedTileEntityType$FixedPointSupplier.get(NamedTileEntityType.java:72) ~[?:1.86.2]
	at dan200.computercraft.shared.util.NamedTileEntityType$FixedPointSupplier.get(NamedTileEntityType.java:58) ~[?:1.86.2]
	at net.minecraft.tileentity.TileEntityType.func_200968_a(TileEntityType.java:90) ~[?:?]
	at dan200.computercraft.shared.common.BlockGeneric.createTileEntity(BlockGeneric.java:89) ~[?:1.86.2]
	at net.minecraftforge.common.extensions.IForgeBlockState.createTileEntity(IForgeBlockState.java:149) ~[?:?]
	at net.minecraft.world.chunk.Chunk.func_177422_i(Chunk.java:366) ~[?:?]
	at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:393) ~[?:?]
	at net.minecraft.world.World.func_175625_s(World.java:840) ~[?:?]
	at dan200.computercraft.shared.computer.blocks.BlockComputerBase.func_220082_b(BlockComputerBase.java:53) ~[?:1.86.2]
```

**Comment by SquidDev** [comment]
As with #366, this is very odd - there's never a situation where classes should just fail to load. I'm 99% sure this isn't a bug with CC:T, but rather a problem with another mod or your environment breaking the class loader.

**Comment by luochen1990** [comment]
@WenXin20 Maybe you can try my workaround solution (#366)
