### ISSUE TITLE
Breaking upward facing monitor crash

### ISSUE THREAD

**Issue by hugeblank** [SquidDev-CC/CC-Tweaked#4]
[crash-2018-01-13_19.06.46-client.txt](https://github.com/SquidDev-CC/CC-Tweaked/files/1628997/crash-2018-01-13_19.06.46-client.txt)
On Project Beta 2 server I broke an upward facing monitor and I crashed.

**Comment by SquidDev** [comment]
Pasting the interesting bit of the log so I don't have to download it each time (grumble, grumble, GitHub)

```
scription: Rendering Block Entity

java.lang.NullPointerException: Rendering Block Entity
	at dan200.computercraft.shared.peripheral.common.TilePeripheralBase.getPeripheralType(TilePeripheralBase.java:68)
	at dan200.computercraft.shared.peripheral.monitor.TileMonitor.getLocalTerminal(TileMonitor.java:282)
	at dan200.computercraft.shared.peripheral.monitor.TileMonitor.getTerminal(TileMonitor.java:260)
	at dan200.computercraft.client.render.TileEntityMonitorRenderer.renderMonitorAt(TileEntityMonitorRenderer.java:97)
	at dan200.computercraft.client.render.TileEntityMonitorRenderer.render(TileEntityMonitorRenderer.java:39)
	at dan200.computercraft.client.render.TileEntityMonitorRenderer.func_192841_a(TileEntityMonitorRenderer.java:28)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_192854_a(TileEntityRendererDispatcher.java:155)
```

**Comment by SquidDev** [comment]
I've tried all sorts of configurations of monitors/single monitors/etc... and am unable to recreate this crash. I'm not entirely sure how it happened, so any additional information would be fantastic.

**Comment by hugeblank** [comment]
hm, I broke it with an atomic reconstructor from mekanism, which has multiple settings for speed at which it can break blocks at. The normal speed is 20, and it breaks the monitors fairly quickly.

That's the only other variable I can think of that would cause the crash.

**Comment by SquidDev** [comment]
I don't believe this has occurred again and I'm unable to reproduce, so I'm going to close for now. If someone else experiences this, please comment and I'll reopen.
