### ISSUE TITLE
runClient fails

### ISSUE THREAD

**Issue by JakobDev** [SquidDev-CC/CC-Tweaked#402]
run Client fails on my computer. setupDecompWorkspace has already ran.
```
jakob@Pluto:~/zw/apitest/CC-Tweaked$ ./gradlew runClient

> Configure project : 
This mapping 'snapshot_20180724' was designed for MC 1.12! Use at your own peril.
Found AccessTransformer: computercraft_at.cfg

> Task :javadoc 
/home/jakob/zw/apitest/CC-Tweaked/src/main/java/dan200/computercraft/api/turtle/ITurtleUpgrade.java:126: warning - Tag @link: reference not found: BlockEvent.BreakEvent
/home/jakob/zw/apitest/CC-Tweaked/src/main/java/dan200/computercraft/api/turtle/ITurtleUpgrade.java:126: warning - Tag @link: reference not found: TurtleBlockEvent.Dig
/home/jakob/zw/apitest/CC-Tweaked/src/main/java/dan200/computercraft/api/turtle/event/TurtleBlockEvent.java:84: warning - Tag @link: reference not found: BlockEvent.BreakEvent
3 warnings

> Task :getAssets 
Current status: 348/1305   26%
Current status: 1063/1305   81%
Current status: 1069/1305   81%
Current status: 1076/1305   82%
Current status: 1144/1305   87%

> Task :runClient 
[15:25:44] [main/INFO] [GradleStart]: Extra: []
[15:25:44] [main/INFO] [GradleStart]: Running with arguments: [--userProperties, {}, --assetsDir, /home/jakob/.gradle/caches/minecraft/assets, --assetIndex, 1.12, --accessToken{REDACTED}, --version, 1.12.2, --tweakClass, net.minecraftforge.fml.common.launcher.FMLTweaker, --tweakClass, net.minecraftforge.gradle.tweakers.CoremodTweaker]
[15:25:44] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[15:25:44] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[15:25:44] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.gradle.tweakers.CoremodTweaker
[15:25:44] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[15:25:44] [main/INFO] [FML]: Forge Mod Loader version 14.23.4.2749 for Minecraft 1.12.2 loading
[15:25:44] [main/INFO] [FML]: Java is OpenJDK 64-Bit Server VM, version 1.8.0_242, running on Linux:amd64:4.4.0-177-generic, installed at /usr/lib/jvm/java-8-openjdk-amd64/jre
[15:25:44] [main/ERROR] [FML]: Apache Maven library folder was not in the format expected. Using default libraries directory.
[15:25:44] [main/ERROR] [FML]: Full: /home/jakob/.gradle/caches/modules-2/files-2.1/org.apache.maven/maven-artifact/3.5.3/7dc72b6d6d8a6dced3d294ed54c2cc3515ade9f4/maven-artifact-3.5.3.jar
[15:25:44] [main/ERROR] [FML]: Trimmed: /home/jakob/.gradle/caches/modules-2/files-2.1/org.apache.maven/maven-artifact/3.5.3/
[15:25:44] [main/INFO] [FML]: Managed to load a deobfuscated Minecraft name- we are in a deobfuscated environment. Skipping runtime deobfuscation
[15:25:44] [main/INFO] [FML]: Detected deobfuscated environment, loading log configs for colored console logs.
2020-04-14 15:25:46,054 main WARN Disabling terminal, you're running in an unsupported environment.
[15:25:46] [main/INFO] [FML]: Ignoring missing certificate for coremod FMLCorePlugin (net.minecraftforge.fml.relauncher.FMLCorePlugin), we are in deobf and it's a forge core plugin
[15:25:46] [main/INFO] [FML]: Ignoring missing certificate for coremod FMLForgePlugin (net.minecraftforge.classloading.FMLForgePlugin), we are in deobf and it's a forge core plugin
[15:25:46] [main/INFO] [FML]: Searching /home/jakob/zw/apitest/CC-Tweaked/run/./mods for mods
[15:25:46] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.gradle.tweakers.CoremodTweaker
[15:25:46] [main/INFO] [GradleStart]: Injecting location in coremod net.minecraftforge.fml.relauncher.FMLCorePlugin
[15:25:46] [main/INFO] [GradleStart]: Injecting location in coremod net.minecraftforge.classloading.FMLForgePlugin
[15:25:46] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:25:46] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[15:25:46] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.gradle.tweakers.AccessTransformerTweaker
[15:25:46] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:25:46] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:25:46] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:25:49] [main/ERROR] [FML]: FML appears to be missing any signature data. This is not a good thing
[15:25:49] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:25:49] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[15:25:51] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.gradle.tweakers.AccessTransformerTweaker
[15:25:51] [main/INFO] [GradleStart]: Remapping AccessTransformer rules...
[15:25:51] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[15:25:51] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[15:25:51] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[15:25:53] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
        at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
        at GradleStart.main(GradleStart.java:25) [start/:?]
Caused by: java.lang.ExceptionInInitializerError
        at org.lwjgl.LinuxSysImplementation.<clinit>(LinuxSysImplementation.java:50) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
        at org.lwjgl.Sys.createImplementation(Sys.java:131) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
        at org.lwjgl.Sys.<clinit>(Sys.java:116) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
        at net.minecraft.client.Minecraft.getSystemTime(Minecraft.java:3158) ~[Minecraft.class:?]
        at net.minecraft.client.main.Main.main(Main.java:42) ~[Main.class:?]
        ... 12 more
Caused by: java.lang.NullPointerException
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1847) ~[?:1.8.0_242]
        at java.lang.Runtime.loadLibrary0(Runtime.java:871) ~[?:1.8.0_242]
        at java.lang.System.loadLibrary(System.java:1124) ~[?:1.8.0_242]
        at java.awt.Toolkit$3.run(Toolkit.java:1636) ~[?:1.8.0_242]
        at java.awt.Toolkit$3.run(Toolkit.java:1634) ~[?:1.8.0_242]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_242]
        at java.awt.Toolkit.loadLibraries(Toolkit.java:1633) ~[?:1.8.0_242]
        at java.awt.Toolkit.<clinit>(Toolkit.java:1670) ~[?:1.8.0_242]
        at org.lwjgl.LinuxSysImplementation.<clinit>(LinuxSysImplementation.java:50) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
        at org.lwjgl.Sys.createImplementation(Sys.java:131) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
        at org.lwjgl.Sys.<clinit>(Sys.java:116) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
        at net.minecraft.client.Minecraft.getSystemTime(Minecraft.java:3158) ~[Minecraft.class:?]
        at net.minecraft.client.main.Main.main(Main.java:42) ~[Main.class:?]
        ... 12 more
Exception in thread "main" [15:25:53] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.reflect.InvocationTargetException
[15:25:53] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:25:53] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[15:25:53] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:25:53] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:        at java.lang.reflect.Method.invoke(Method.java:498)
[15:25:53] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:        at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
[15:25:53] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:        at GradleStart.main(GradleStart.java:25)
[15:25:53] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[15:25:53] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]:        at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[15:25:53] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]:        at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[15:25:53] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]:        at java.lang.Runtime.exit(Runtime.java:108)
[15:25:53] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]:        at java.lang.System.exit(System.java:973)
[15:25:53] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]:        at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[15:25:53] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]:        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[15:25:53] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]:        ... 6 more


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runClient'.
> Process 'command '/usr/lib/jvm/java-8-openjdk-amd64/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 54s
13 actionable tasks: 11 executed, 2 up-to-date
jakob@Pluto:~/zw/apitest/CC-Tweaked$ 
```
It looks like you need to update the gradle configuration to work with the latest version.

**Comment by Lemmmy** [comment]
I had this issue too, downgrade to JDK 8_u232.

**Comment by SquidDev** [comment]
This happens in Minecraft code, due to Java changing some class loader internals. Forge no longer supports 1.12, so I believe this is unlikely to be fixed. As Lem says, I'm afraid the only solution I'm aware of is to run a Java version pre 242.

**Comment by JakobDev** [comment]
Where do I get Version u232 for Linux?

**Comment by SquidDev** [comment]
Easiest way is to use the [Zulu builds](https://www.azul.com/downloads/zulu-community/?version=java-8-lts&os=linux&architecture=x86-64-bit&package=jdk&show-old-builds=true). [This](https://cdn.azul.com/zulu/bin/zulu8.42.0.23-ca-jdk8.0.232-linux_x64.tar.gz) should be the correct .tar.gz for 8u232.

**Comment by JakobDev** [comment]
@SquidDev Thanks

**Comment by SquidDev** [comment]
MinecraftForge/MinecraftForge#6473 seems to suggest the next Java release will also fix this, which should make things easier again.
