### ISSUE TITLE
Turning on/rebooting a computer crashes the client

### ISSUE THREAD

**Issue by Lemmmy** [SquidDev-CC/CC-Tweaked#414]
MC 1.12.2, CC:T 1.86.2, `custom/sc` branch

Turning on a computer while the terminal is opened, or rebooting a computer (Ctrl+R, `reboot` command) causes this renderer-related client crash:

```
java.lang.NullPointerException: Rendering screen
	at dan200.computercraft.client.gui.FixedWidthFontRenderer.drawQuad(FixedWidthFontRenderer.java:97)
	at dan200.computercraft.client.gui.FixedWidthFontRenderer.drawBackground(FixedWidthFontRenderer.java:131)
	at dan200.computercraft.client.gui.FixedWidthFontRenderer.drawString(FixedWidthFontRenderer.java:152)
	at dan200.computercraft.client.gui.FixedWidthFontRenderer.drawTerminalWithoutCursor(FixedWidthFontRenderer.java:217)
	at dan200.computercraft.client.gui.FixedWidthFontRenderer.drawTerminal(FixedWidthFontRenderer.java:261)
	at dan200.computercraft.client.gui.FixedWidthFontRenderer.drawTerminal(FixedWidthFontRenderer.java:275)
	at dan200.computercraft.client.gui.widgets.WidgetTerminal.draw(WidgetTerminal.java:335)
	at dan200.computercraft.client.gui.GuiComputer.func_73863_a(GuiComputer.java:153)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

Seems very related to #413 - could be the exact same issue.

**Comment by Lemmmy** [comment]
Sorry, this *is* #413 - OpusOS blits its logo with a space on startup. Apologies for the dupe.
