### ISSUE TITLE
Server crash when using a turtle to mine

### ISSUE THREAD

**Issue by OTRD5k** [SquidDev-CC/CC-Tweaked#585]
Mc 1.15.2
Forge 31.2.46
CC 1.94.0

I don't have specific reproduction steps unfortunately. At a glance, it looks like the turtle tried to mine out air somehow?

```
[18Nov2020 05:58:52.689] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking block entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:853) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) ~[?:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
Caused by: java.lang.IllegalArgumentException: Cannot get property DirectionProperty{name=facing, clazz=class net.minecraft.util.Direction, values=[north, south, west, east]} as it does not exist in Block{minecraft:air}
        at net.minecraft.state.StateHolder.func_177229_b(SourceFile:93) ~[?:?]
        at dan200.computercraft.shared.turtle.blocks.TileTurtle.getDirection(TileTurtle.java:317) ~[?:1.94.0]
        at dan200.computercraft.shared.turtle.core.TurtleBrain.getDirection(TurtleBrain.java:404) ~[?:1.94.0]
        at dan200.computercraft.shared.turtle.upgrades.TurtleTool.stopConsuming(TurtleTool.java:272) ~[?:1.94.0]
        at dan200.computercraft.shared.turtle.upgrades.TurtleTool.dig(TurtleTool.java:256) ~[?:1.94.0]
        at dan200.computercraft.shared.turtle.upgrades.TurtleTool.useTool(TurtleTool.java:94) ~[?:1.94.0]
        at dan200.computercraft.shared.turtle.core.TurtleToolCommand.execute(TurtleToolCommand.java:39) ~[?:1.94.0]
        at dan200.computercraft.shared.turtle.core.TurtleBrain.updateCommands(TurtleBrain.java:770) ~[?:1.94.0]
        at dan200.computercraft.shared.turtle.core.TurtleBrain.update(TurtleBrain.java:130) ~[?:1.94.0]
        at dan200.computercraft.shared.turtle.blocks.TileTurtle.func_73660_a(TileTurtle.java:216) ~[?:1.94.0]
        at net.minecraft.world.World.func_217391_K(World.java:473) ~[?:?]
        at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:368) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849) ~[?:?]
        ... 4 more
```

**Comment by SquidDev** [comment]
> At a glance, it looks like the turtle tried to mine out air somehow?

Oh no, if only it were that simple. The turtle _itself_ is air, which really shouldn't happen.

The only thing I can think of is if the turtle was destroyed by the block it mined, for instance by an explosion or other block shenanigans. Don't know if you can think of any blocks in your pack which have this behaviour?

**Comment by OTRD5k** [comment]
Hey, I managed to reproduce this by making a turtle mine into a lucky block. Occasionally it will do something that includes destroying the turtle - and thus crashing the server.

**Comment by mjmfighter** [comment]
I have had this exact error happen to me now twice in the Valhelsia 2 modpack.  Had a turtle out doing a quarry and crashed to this error.  Unfortunately when I started the server up again and found where the turtle should have been, it was gone.

I have tried to recreate with the Stella Arcanum ore as mentioned in #462, but I haven't been able to recreate the error.
