### ISSUE TITLE
1.95.2 datagen issue (with CC-Tweaked as mod dependency)

### ISSUE THREAD

**Issue by desht** [SquidDev-CC/CC-Tweaked#701]
## Useful information to include:
 - Minecraft version - 1.16.5
 - CC: Tweaked version - 1.94.0 and 1.95.2

Hi - I have CC-Tweaked as a PneumaticCraft: Repressurized mod dependency, and I've been pulling in CC-Tweaked 1.94.0 until recently with no problems.

Yesterday I updated that to 1.95.2, but this broke my datagen (`./gradlew runData`), with this exception:
```
[14:49:32] [main/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Caught exception during event net.minecraftforge.fml.event.lifecycle.GatherDataEvent@2ed0f3ec dispatch for modid computercraft
java.lang.IllegalStateException: Model at computercraft:block/monitor_base does not exist
        at com.google.common.base.Preconditions.checkState(Preconditions.java:518) ~[guava-21.0.jar:?] {}
        at net.minecraftforge.client.model.generators.ModelFile.assertExistence(ModelFile.java:47) ~[forge-1.16.5-36.0.4_mapped_snapshot_20201028-1.16.3-recomp.jar:?] {re:classloading}
        at net.minecraftforge.client.model.generators.ModelProvider.getExistingFile(ModelProvider.java:357) ~[forge-1.16.5-36.0.4_mapped_snapshot_20201028-1.16.3-recomp.jar:?] {re:classloading}
        at dan200.computercraft.data.BlockModelProvider.<init>(BlockModelProvider.java:31) ~[cc-tweaked-1.16.4-1.95.2_mapped_snapshot_20201028-1.16.3.jar:1.95.2] {re:classloading}
        at dan200.computercraft.data.Generators.gather(Generators.java:26) ~[cc-tweaked-1.16.4-1.95.2_mapped_snapshot_20201028-1.16.3.jar:1.95.2] {re:classloading}
        at net.minecraftforge.eventbus.ASMEventHandler_41_Generators_gather_GatherDataEvent.invoke(.dynamic) ~[?:?] {}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[forge-1.16.5-36.0.4_mapped_snapshot_20201028-1.16.3-recomp.jar:36.0] {re:classloading}
        at net.minecraftforge.fml.ModLoader.lambda$runEventGenerator$33(ModLoader.java:318) ~[forge-1.16.5-36.0.4_mapped_snapshot_20201028-1.16.3-recomp.jar:?] {re:classloading}
        at java.util.HashMap.forEach(HashMap.java:1289) ~[?:1.8.0_201] {}
        at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:229) ~[forge-1.16.5-36.0.4_mapped_snapshot_20201028-1.16.3-recomp.jar:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.runEventGenerator(ModLoader.java:318) ~[forge-1.16.5-36.0.4_mapped_snapshot_20201028-1.16.3-recomp.jar:?] {re:classloading}
        at net.minecraftforge.fml.DatagenModLoader.begin(DatagenModLoader.java:60) ~[forge-1.16.5-36.0.4_mapped_snapshot_20201028-1.16.3-recomp.jar:?] {re:classloading}
        at net.minecraft.data.Main.main(Main.java:43) ~[forge-1.16.5-36.0.4_mapped_snapshot_20201028-1.16.3-recomp.jar:?] {re:classloading}
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201] {}
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201] {}
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201] {}
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201] {}
        at net.minecraftforge.userdev.FMLUserdevDataLaunchProvider.lambda$launchService$0(FMLUserdevDataLaunchProvider.java:51) ~[forge-1.16.5-36.0.4_mapped_snapshot_20201028-1.16.3-recomp.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
        at net.minecraftforge.userdev.LaunchTesting.main(LaunchTesting.java:105) [forge-1.16.5-36.0.4_mapped_snapshot_20201028-1.16.3-recomp.jar:?] {}
```

I guess something's changed between 1.94.0 and 1.95.2 wrt model datagen?  Something not quite working as expected anyway.  I've downgraded the build dep back to 1.94.0 for now and my datagen is working again.

Currently using Forge 36.0.4 and MC 1.16.5.

**Comment by SquidDev** [comment]
So c8aeddedd4ed430f9cb6428676ebb4fa39834182 switched monitor model generation over to using data generators, which I guess is the root cause here.

I had rather assumed Forge wouldn't fire the `GatherDataEvent` event for any mod not in `--mod`, but it looks like it fires the event just doesn't run the generators. I guess I'll need to make our fetching of various `ModelFile`s lazy.
