### ISSUE TITLE
it is not allowing me to add the mod  to my server

### ISSUE THREAD

**Issue by PPerson314** [SquidDev-CC/CC-Tweaked#764]
I am running a 1.16.5 spigot server, and I installed the .jar file into the /plugins directory
It is giving me the error: 
Could not load 'plugins\cc-tweaked-1.16.4-1.95.3.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:160) ~[spigot.jar:3016-Spigot-73fb609-ea050e6]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:144) ~[spigot.jar:3016-Spigot-73fb609-ea050e6]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:382) ~[spigot.jar:3016-Spigot-73fb609-ea050e6]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:185) ~[spigot.jar:3016-Spigot-73fb609-ea050e6]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:809) ~[spigot.jar:3016-Spigot-73fb609-ea050e6]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot.jar:3016-Spigot-73fb609-ea050e6]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml

**Comment by SquidDev** [comment]
CC:T has numerous client side modifications too (such as the main computer GUI) and so requires [MinecraftForge](https://files.minecraftforge.net). It will not work with server side only modding frameworks like Bukkit or Spigot.

**Comment by PPerson314** [comment]
ok thank you
so every player has to have the mod installed as well?

**Comment by SquidDev** [comment]
Yes.
