### ISSUE TITLE
Monitor render issue

### ISSUE THREAD

**Issue by frank89722** [SquidDev-CC/CC-Tweaked#879]
### Minecraft Version

1.16.x

### Version

1.98.0

### Details

Forge-36.2.2

1.97.0:
![image](https://user-images.githubusercontent.com/10683361/127831506-521c4d70-dd4a-492e-9d8e-6613590e4bfd.png)

After updated to 1.98.0:
![image](https://user-images.githubusercontent.com/10683361/127830358-a67a042e-476e-4efe-8757-c5dc337a4e01.png)

Here is some server-side log:
```
[02.08 08:30:00] [Server] [Server thread/FATAL] [minecraft/ThreadTaskExecutor]: Error executing task on Server
[02.08 08:30:00] [Server] java.lang.NullPointerExceptionCannot invoke "dan200.computercraft.shared.peripheral.monitor.TileMonitor.resize(int, int)" because "right" is null
[02.08 08:30:00] [Server] 	at dan200.computercraft.shared.peripheral.monitor.TileMonitor.contract(TileMonitor.java:624) ~[computercraft:1.98.{re:classloading}
[02.08 08:30:00] [Server] 	at dan200.computercraft.shared.peripheral.monitor.TileMonitor.contractNeighbours(TileMonitor.java:559) ~[computercraft:1.98.{re:classloading}
[02.08 08:30:00] [Server] 	at dan200.computercraft.shared.peripheral.monitor.TileMonitor.destroy(TileMonitor.java:92) ~[computercraft:1.98.{re:classloading}
[02.08 08:30:00] [Server] 	at dan200.computercraft.shared.common.BlockGeneric.func_196243_a(BlockGeneric.java:46) ~[computercraft:1.98.{re:classloading}
[02.08 08:30:00] [Server] 	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_196947_b(AbstractBlock.java:616) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:betterweather.mixins.json:block.MixinAbstractBlockState,pl:mixin:APP:libx.mixins.json:MixinAbstractBlockState,pl:mixin:APP:kubejs-common.mixins.json:BlockStateBaseMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.AbstractBlockStateMixin,pl:mixin:APP:ferritecore.blockstatecache.mixin.json:AbstractBlockStateMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[02.08 08:30:00] [Server] 	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:267) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterweather.mixins.json:chunk.MixinChunk,pl:mixin:A,pl:runtimedistcleaner:A}
[02.08 08:30:00] [Server] 	at net.minecraft.world.World.func_241211_a_(World.java:199) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,pl:mixin:APP:betterweather.mixins.json:MixinWorld,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[02.08 08:30:00] [Server] 	at net.minecraft.world.World.func_180501_a(World.java:176) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,pl:mixin:APP:betterweather.mixins.json:MixinWorld,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[02.08 08:30:00] [Server] 	at net.minecraftforge.common.extensions.IForgeBlock.removedByPlayer(IForgeBlock.java:214) ~[forge:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
[02.08 08:30:00] [Server] 	at net.minecraftforge.common.extensions.IForgeBlockState.removedByPlayer(IForgeBlockState.java:157) ~[forge:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
[02.08 08:30:00] [Server] 	at net.minecraft.server.management.PlayerInteractionManager.removeBlock(PlayerInteractionManager.java:271) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:libx.mixins.json:MixinPlayerInteractionManager,pl:mixin:APP:kubejs-common.mixins.json:PlayerInteractionManagerMixin,pl:mixin:A}
[02.08 08:30:00] [Server] 	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:254) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:libx.mixins.json:MixinPlayerInteractionManager,pl:mixin:APP:kubejs-common.mixins.json:PlayerInteractionManagerMixin,pl:mixin:A}
[02.08 08:30:00] [Server] 	at net.minecraft.server.management.PlayerInteractionManager.func_229860_a_(PlayerInteractionManager.java:220) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:libx.mixins.json:MixinPlayerInteractionManager,pl:mixin:APP:kubejs-common.mixins.json:PlayerInteractionManagerMixin,pl:mixin:A}
[02.08 08:30:00] [Server] 	at net.minecraft.server.management.PlayerInteractionManager.func_225416_a(PlayerInteractionManager.java:168) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:libx.mixins.json:MixinPlayerInteractionManager,pl:mixin:APP:kubejs-common.mixins.json:PlayerInteractionManagerMixin,pl:mixin:A}
[02.08 08:30:00] [Server] 	at net.minecraft.network.play.ServerPlayNetHandler.func_147345_a(ServerPlayNetHandler.java:929) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_server_entity_interact,xf:fml:astralsorcery:allow_entity_interaction,pl:mixin:A}
[02.08 08:30:00] [Server] 	at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:40) ~[?:?] {re:classloading}
[02.08 08:30:00] [Server] 	at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:10) ~[?:?] {re:classloading}
[02.08 08:30:00] [Server] 	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
[02.08 08:30:00] [Server] 	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
[02.08 08:30:00] [Server] 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
[02.08 08:30:00] [Server] 	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:mixin,re:computing_frames,re:classloading}
[02.08 08:30:00] [Server] 	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[02.08 08:30:00] [Server] 	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[02.08 08:30:00] [Server] 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
[02.08 08:30:00] [Server] 	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[02.08 08:30:00] [Server] 	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[02.08 08:30:00] [Server] 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
[02.08 08:30:00] [Server] 	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:696) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[02.08 08:30:00] [Server] 	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[02.08 08:30:00] [Server] 	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[02.08 08:30:00] [Server] 	at java.lang.Thread.run(Thread.java:832) [?:?] {}
```

**Comment by SquidDev** [comment]
Thanks for the report. I really need to rewrite monitor resizing one day, so it actually behaves in a way I understand. This should work for now though.
