### ISSUE TITLE
Crash with Project: Red Compat Module

### ISSUE THREAD

**Issue by minz1** [SquidDev-CC/CC-Tweaked#99]
```
Time: 1/10/19 2:34 PM
Description: Exception ticking world

java.lang.NoSuchMethodError: mrtjp.projectred.api.ITransmissionAPI.getBundledInput(Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/EnumFacing;)[B
	at mrtjp.projectred.compatibility.computercraft.CCPRBundledRedstoneProvider$.getBundledRedstoneOutput(PluginComputerCraft.scala:45)
	at dan200.computercraft.ComputerCraft.getBundledRedstoneOutput(ComputerCraft.java:799)
	at dan200.computercraft.shared.util.RedstoneUtil.getBundledRedstoneOutput(RedstoneUtil.java:25)
	at dan200.computercraft.shared.computer.blocks.TileComputerBase.updateSideInput(TileComputerBase.java:330)
	at dan200.computercraft.shared.computer.blocks.TileComputerBase.updateInput(TileComputerBase.java:352)
	at dan200.computercraft.shared.computer.blocks.TileComputerBase.createServerComputer(TileComputerBase.java:485)
	at dan200.computercraft.shared.computer.blocks.TileComputerBase.writeDescription(TileComputerBase.java:532)
	at dan200.computercraft.shared.common.TileGeneric.func_189518_D_(TileGeneric.java:189)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187273_a(PlayerChunkMapEntry.java:288)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187280_d(PlayerChunkMapEntry.java:250)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(PlayerChunkMap.java:182)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at net.optifine.override.WorldServerOF.func_72835_b(WorldServerOF.java:39)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

```

I believe the issue lies with the Project: Red Compat module's use of the older API. 
https://github.com/MrTJP/ProjectRed/tree/master/src/dan200/computercraft/api

**Comment by minz1** [comment]
Actually, I think the issue lies elsewhere. Sorry!

**Comment by minz1** [comment]
[20:07:37] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:762) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
Caused by: java.lang.NoSuchMethodError: mrtjp.projectred.api.ITransmissionAPI.getBundledInput(Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/EnumFacing;)[B
	at mrtjp.projectred.compatibility.computercraft.CCPRBundledRedstoneProvider$.getBundledRedstoneOutput(PluginComputerCraft.scala:45) ~[CCPRBundledRedstoneProvider$.class:?]
	at dan200.computercraft.ComputerCraft.getBundledRedstoneOutput(ComputerCraft.java:799) ~[ComputerCraft.class:?]
	at dan200.computercraft.shared.util.RedstoneUtil.getBundledRedstoneOutput(RedstoneUtil.java:25) ~[RedstoneUtil.class:?]
	at dan200.computercraft.shared.computer.blocks.TileComputerBase.updateSideInput(TileComputerBase.java:330) ~[TileComputerBase.class:?]
	at dan200.computercraft.shared.computer.blocks.TileComputerBase.updateInput(TileComputerBase.java:352) ~[TileComputerBase.class:?]
	at dan200.computercraft.shared.computer.blocks.TileComputerBase.createServerComputer(TileComputerBase.java:485) ~[TileComputerBase.class:?]
	at dan200.computercraft.shared.computer.blocks.TileComputerBase.writeDescription(TileComputerBase.java:532) ~[TileComputerBase.class:?]
	at dan200.computercraft.shared.common.TileGeneric.func_189518_D_(TileGeneric.java:189) ~[TileGeneric.class:?]
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187273_a(PlayerChunkMapEntry.java:288) ~[ot.class:?]
	at net.minecraft.server.management.PlayerChunkMapEntry.func_18728https://www.spongepowered.org/downloads/spongeforge/bleeding/1.12.20_d(PlayerChunkMapEntry.java:250) ~[ot.class:?]
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:115) ~[ou.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756) ~[MinecraftServer.class:?]
	... 4 more

Nevermind! Seems to be an issue even without Optifine.

**Comment by SquidDev** [comment]
I'm fairly sure this is on their end - I don't provide any of the integration with ProjectRed, but I'll have a look into it.

**Comment by minz1** [comment]
You're right, something else was going on. There was another mod killing it since it used an older version of the Project: Red API.

**Comment by SquidDev** [comment]
Great! Glad you managed to figure out what was going on :).
